import {test,expect} from "bun:test"
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from "node:fs"
import {tmpdir} from "node:os"
import {join} from "node:path"
import {projectIdentity} from "../quest/project"
import {QUEST_TOOL_INPUT} from "../quest/tool-schema.mjs"
const wrapper=join(import.meta.dir,"..","harnesses","opencode-mcp-stdio.mjs")
test("MCP uses the native schema and five operations with structured results and retry identity",async()=>{
 const root=mkdtempSync(join(tmpdir(),"quest-adapters-")),main=join(root,"project"),ledger=join(root,"ledger");mkdirSync(main);mkdirSync(join(root,"auth"));for(const args of [["init",main],["-C",main,"-c","user.name=Fixture","-c","user.email=fixture@example.invalid","commit","--allow-empty","-m","Fixture"]])if(Bun.spawnSync(["git",...args],{windowsHide:true}).exitCode!==0)throw Error("Git fixture failed")
 const server=Bun.serve({port:0,fetch(request){if(new URL(request.url).pathname==="/api/session/parent")return Response.json({data:{id:"parent",location:{directory:main}}});return new Response("Unexpected route",{status:404})}}),policy=join(root,"policy.json");writeFileSync(policy,JSON.stringify({version:1,commandsByProject:{[projectIdentity(main).id]:{verify:{description:"Fixture check",argv:[process.execPath,"-e","require('fs').writeFileSync('verified.txt','verified')"],timeoutMilliseconds:5000}}}}))
 const call=async(id:number,input:any,method="tools/call")=>{const proc=Bun.spawn(["node",wrapper],{cwd:main,env:{...process.env,OPENCODE_SERVER_URL:"http://127.0.0.1:"+server.port,OPENCODE_PARENT_SESSION_ID:"parent",OPENCODE_MCP_INVOCATION_ID:"fixture",OPENCODE_QUEST_ROOT:ledger,OPENCODE_DISPATCH_POLICY:policy,OPENCODE_ACCOUNT_DISCOVERY_ROOT:join(root,"auth")},windowsHide:true,stdin:"pipe",stdout:"pipe",stderr:"pipe"});proc.stdin.write(JSON.stringify({jsonrpc:"2.0",id,method,params:method==="tools/call"?{name:"quest",arguments:input}:{}})+"\n");proc.stdin.end();const[code,out,err]=await Promise.all([proc.exited,new Response(proc.stdout).text(),new Response(proc.stderr).text()]);if(code!==0)throw Error(err);return JSON.parse(out).result}
 try{const tools=await call(0,{},"tools/list");expect(tools.tools.find((t:any)=>t.name==="quest").inputSchema).toEqual(QUEST_TOOL_INPUT);expect(tools.tools.some((t:any)=>t.name==="pick_model")).toBe(false);const input={action:"create",create:{title:"Adapter",description:"Check unified API",steps:[{id:"verify",title:"Check",detail:"Write the fixture output with the configured command",commandID:"verify"}]}};const created=await call(1,input);expect(created.isError).toBeUndefined();const q=created.structuredContent;expect(q.description).toBe("Check unified API");expect(q.steps[0].detail).toContain("configured command");expect((await call(1,input)).structuredContent.id).toBe(q.id);expect((await call(2,{action:"list"})).structuredContent.items).toHaveLength(1);expect((await call(3,{action:"update",id:q.id,update:{steps:[{id:"verify"}]}})).isError).toBe(true);expect((await call(4,{action:"get",id:q.id})).structuredContent.steps[0].state).toBe("pending");expect((await call(5,{action:"run",id:q.id})).structuredContent.state).toBe("completed");expect((await call(6,{action:"update",id:q.id,update:{reward:"Fixture complete"}})).isError).toBeUndefined();const reward=(await call(7,{action:"get",id:q.id,inspect:{section:"reward"}})).structuredContent;expect(JSON.parse(reward.text)).toBe("Fixture complete");expect(reward.nextOffset).toBeNull();const result=(await call(8,{action:"get",id:q.id,inspect:{section:"changes"}})).structuredContent;expect(JSON.parse(result.text).some((c:any)=>c.files.some((f:any)=>f.path==="verified.txt"))).toBe(true);expect(result.ledgerRoot).toBeUndefined()
 }finally{server.stop(true);rmSync(root,{recursive:true,force:true})}
},30000)
