import {test,expect} from 'bun:test'
import {mkdtempSync,rmSync,mkdirSync,writeFileSync,readFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {spawnSync} from 'node:child_process'
import {QuestStore} from '../quest/store'
import {questsAPI} from '../quest/api'
import {projectIdentity} from '../quest/project'
import {trackedStart,configureLearning,collectWorkflowOutcomes} from '../quest/outcome-tracking'
import {readWorkflowOutcomes,judgeWorkflowRun} from '../usage/workflow-outcomes'
import {outcomeTool,workSupplyTool} from '../quest/adaptive-tools'
import {typedQuestTool} from '../quest/typed-tool'
import type {LedgerRow} from '../usage/passive-ledger'
function fixture(){const root=mkdtempSync(join(tmpdir(),'quest-adaptive-')),main=join(root,'repo');mkdirSync(main);const p=spawnSync('git',['init',main],{windowsHide:true,encoding:'utf8'});if(p.status!==0)throw Error(p.stderr);const store=new QuestStore(join(root,'ledger')),context={project:projectIdentity(main),sessionID:'giver',requestID:'request'},host={get:async()=>({location:{directory:main}}),create:async()=>({id:'worker'}),prompt:async()=>({})};const start=trackedStart(store,async i=>{store.apply(i.quest.id,'session-claimed',{callID:i.runID,runID:i.runID,sessionID:'worker',parentID:'giver',providerID:'provider',modelID:'model'},'fixture');return {sessionID:'worker'}});const api=questsAPI(store,context,start),q=api.create({title:'Measured work',description:'Implement and verify',steps:[{id:'a',title:'Implement'},{id:'b',title:'Independent'},{id:'integrate',title:'Integrate',needs:['a','b']}]});return {root,main,store,context,host,api,q,file:join(root,'outcomes.json'),clean:()=>rmSync(root,{recursive:true,force:true})}}
test('passive integration deduplicates exact session counters, separates judgment and retains late tokens',async()=>{const f=fixture();try{configureLearning(f.store,f.context,f.q.id,{a:['debugging']});const run=await f.api.run(f.q.id,{stepIDs:['a'],model:'provider/model'});const startedAt=JSON.parse(readFileSync(join(f.store.runtime,'workflow-tracking.json'),'utf8')).runs[0].startedAt;const row:LedgerRow={id:'r',source:'opencode',sessionID:'worker',accountID:'account',regime:'plan1',startedAt,at:Date.now(),route:{providerID:'provider',modelID:'model',harness:'native',reasoning:'high',serviceTier:'default'},kind:'generation',state:'completed',tokens:{input:10,cacheRead:20,cacheWrite:null,output:5,reasoning:2}};f.store.apply(f.q.id,'stage-state',{stageID:'a',status:'done'},'fixture');f.store.apply(f.q.id,'session-state',{callID:run.runID,state:'completed'},'fixture');let now=Date.now()+10;const capture=collectWorkflowOutcomes(f.store,{file:f.file,now,rows:()=>[row,row,{...row,id:'host',source:'opencode-host',tokens:{...row.tokens,input:999}}]});expect(capture.diagnostics).toEqual([]);let measured=readWorkflowOutcomes(f.file).runs[0];expect(measured.taskTags).toEqual(['debugging']);expect(measured.observation!.tokens.input).toBe(10);expect(measured.observation!.tokens.cacheWrite).toBeNull();expect(measured.judgment).toBeNull();judgeWorkflowRun(f.file,{runID:run.runID,judgedAt:now+1,accepted:true,firstPass:true,reviewer:'giver',verification:[{command:'bun test',exitCode:0,artifact:'checks.log'}]});const before=readFileSync(f.file,'utf8');const ended=readWorkflowOutcomes(f.file).runs[0].observation!.completedAt;expect(collectWorkflowOutcomes(f.store,{file:f.file,now:now+5,rows:()=>[row]}).observed).toBe(0);expect(readFileSync(f.file,'utf8')).toBe(before);row.tokens.cacheWrite=3;now+=10;expect(collectWorkflowOutcomes(f.store,{file:f.file,now,rows:()=>[row]}).diagnostics).toEqual([]);measured=readWorkflowOutcomes(f.file).runs[0];expect(measured.observation!.tokens.cacheWrite).toBe(3);expect(measured.observation!.completedAt).toBe(ended);expect(measured.judgment!.accepted).toBe(true);expect(measured.route.version).toBe('unknown')}finally{f.clean()}})
test('mixed routes and invalid timestamps cannot become precise token attribution',async()=>{const f=fixture();try{const run=await f.api.run(f.q.id,{stepIDs:['a'],model:'provider/model'});const startedAt=Date.now(),row:LedgerRow={id:'r',source:'opencode',sessionID:'worker',accountID:'account',startedAt,at:startedAt,route:{providerID:'provider',modelID:'model'},kind:'generation',state:'completed',tokens:{input:10,cacheRead:0,cacheWrite:0,output:3,reasoning:0}};f.store.apply(f.q.id,'session-state',{callID:run.runID,state:'completed'},'fixture');expect(collectWorkflowOutcomes(f.store,{file:f.file,now:Date.now()+10,rows:()=>[row,{...row,id:'other',route:{providerID:'provider',modelID:'other'}}]}).diagnostics.join(' ')).toContain('mixed route');expect(readWorkflowOutcomes(f.file).runs[0].observation!.routeConsistent).toBe(false);expect(readWorkflowOutcomes(f.file).runs[0].observation!.tokens.input).toBeNull();expect(collectWorkflowOutcomes(f.store,{file:f.file,now:Date.now()+20,rows:()=>[{...row,at:NaN}]}).diagnostics.join(' ')).toContain('timestamp')}finally{f.clean()}})
test('typed parallel dispatch rejects shared mode and ready supply respects dependencies',async()=>{const f=fixture();try{const settings=join(f.root,'settings.json');writeFileSync(settings,JSON.stringify({version:1,workspaceMode:'shared'}));const tool=typedQuestTool(f.store,f.host,{settingsFile:settings,startRun:async()=>{throw Error('must not launch')}});await expect(tool.execute({action:'run',id:f.q.id,run:{continue:true,maxConcurrent:2,model:'p/m'}},{sessionID:'giver',id:'dispatch'})).rejects.toThrow('isolated worktrees');const supply=await workSupplyTool(f.store,f.host).execute({}, {sessionID:'giver',id:'supply'});expect(supply.output.readySteps).toBe(2);expect(supply.output.items[0].readySteps.map((s:any)=>s.id)).toEqual(['a','b']);f.store.apply(f.q.id,'session-planned',{callID:'existing',runID:'existing',deliverables:['a']},'fixture');const next=await workSupplyTool(f.store,f.host).execute({}, {sessionID:'giver',id:'supply2'});expect(next.output.readySteps).toBe(1);expect(next.output.activeOrUncertainRuns).toBe(1);await expect(outcomeTool(f.store,f.host).execute({action:'judge',questID:f.q.id,runID:'foreign',accepted:true},{sessionID:'giver',id:'judge'})).rejects.toThrow('not owned')}finally{f.clean()}})
import {QuestContinuation} from '../quest/continuation'
test('persisted parallel intent keeps its worktree guard after a rejected or ordinary metadata request',async()=>{const f=fixture();try{const settings=join(f.root,'mode.json');writeFileSync(settings,JSON.stringify({version:1,workspaceMode:'worktree'}));let launches=0;const start=trackedStart(f.store,async()=>({sessionID:'parallel-'+(++launches)}),settings);configureLearning(f.store,f.context,f.q.id,undefined,2);const continuation=new QuestContinuation(f.store,start,{refresh:async()=>({accounts:[]}) as any});await continuation.run(f.q.id,{model:'p/m',maxConcurrent:2},f.context);expect(launches).toBe(2);configureLearning(f.store,f.context,f.q.id,undefined,1);for(const run of f.store.read(f.q.id)!.sessions){for(const id of run.deliverables)f.store.apply(f.q.id,'stage-state',{stageID:id,status:'done'},'fixture');f.store.apply(f.q.id,'session-state',{callID:run.callID,state:'completed'},'fixture')}writeFileSync(settings,JSON.stringify({version:1,workspaceMode:'shared'}));await continuation.tick();expect(launches).toBe(2);expect(f.store.read(f.q.id)!.sessions.at(-1)!.result).toContain('isolated worktrees')}finally{f.clean()}})
test('outcome tool retries preserve original judgment timestamp and reject a changed verdict',async()=>{const f=fixture();try{const run=await f.api.run(f.q.id,{stepIDs:['a'],model:'provider/model'});f.store.apply(f.q.id,'stage-state',{stageID:'a',status:'done'},'fixture');f.store.apply(f.q.id,'session-state',{callID:run.runID,state:'completed'},'fixture');collectWorkflowOutcomes(f.store,{file:f.file,rows:()=>[]});const tool=outcomeTool(f.store,f.host,{file:f.file}),input={action:'judge',questID:f.q.id,runID:run.runID,accepted:true,firstPass:true,verification:[{command:'bun test',exitCode:0,artifact:'verification.log'}]};const a=await tool.execute(input,{sessionID:'giver',id:'judgment'});await Bun.sleep(3);const b=await tool.execute(input,{sessionID:'giver',id:'judgment'});expect(b.output.run.judgment).toEqual(a.output.run.judgment);await expect(tool.execute({...input,accepted:false},{sessionID:'giver',id:'changed'})).rejects.toThrow('different evaluator judgment')}finally{f.clean()}})
