import {test,expect} from "bun:test"
import {mkdtempSync,mkdirSync,rmSync} from "node:fs"
import {tmpdir} from "node:os"
import {join} from "node:path"
import {QuestStore} from "../quest/store"
import {SessionGuidance} from "../quest/session-guidance"
function fixture(){const root=mkdtempSync(join(tmpdir(),"guidance-")),workspace=join(root,"worker");mkdirSync(workspace);const store=new QuestStore(root),project={id:"project",root},context={project,sessionID:"giver",requestID:"request"};store.create({id:"00000000000000000000000001",title:"Implement",objective:"Work",project,integrationOwner:"giver",sessions:[{callID:"run",runID:"run",sessionID:"worker",parentID:"giver",runtime:"native",role:"general",state:"executing",scope:{worktree:workspace},evidence:[],deliverables:[],attempt:1,updatedAt:new Date().toISOString()}]});let prompts:any[]=[];const host={create:async()=>null,get:async()=>({id:"worker",location:{directory:workspace}}),prompt:async(i:any)=>{prompts.push(i);return{id:i.id,sessionID:i.sessionID}}};return{root,workspace,store,context,host,prompts,input:{questID:"00000000000000000000000001",runID:"run",text:"Investigate the failing parser case"},cleanup:()=>rmSync(root,{recursive:true,force:true})}}
test("stable guidance defaults to queue and coalesces concurrent/reloaded retries",async()=>{const f=fixture();try{const guide=new SessionGuidance(f.store,f.host,{supported:true});const [a,b]=await Promise.all([guide.send(f.context,f.input),guide.send(f.context,f.input)]);expect(a.id).toBe(b.id);expect(f.prompts).toHaveLength(1);expect(f.prompts[0].delivery).toBe("queue");expect(new SessionGuidance(f.store,f.host,{supported:true}).status(f.context,"00000000000000000000000001")[0].state).toBe("submitted");await guide.send(f.context,f.input);expect(f.prompts).toHaveLength(1)}finally{f.cleanup()}})
test("unknown delivery survives reload without automatic retry",async()=>{const f=fixture();try{f.host.prompt=async(i:any)=>{f.prompts.push(i);throw Error("connection closed")};const guide=new SessionGuidance(f.store,f.host,{supported:true});expect((await guide.send(f.context,f.input)).state).toBe("unknown");expect((await new SessionGuidance(f.store,f.host,{supported:true}).send(f.context,f.input)).state).toBe("unknown");expect(f.prompts).toHaveLength(1)}finally{f.cleanup()}})
test("only exact owned active session gets guidance and unverified hosts fail closed",async()=>{const f=fixture();try{await expect(new SessionGuidance(f.store,f.host).send(f.context,f.input)).rejects.toThrow("not been verified");const guide=new SessionGuidance(f.store,f.host,{supported:true});await expect(guide.send({...f.context,sessionID:"foreign"},f.input)).rejects.toThrow("owning giver");await expect(guide.send({...f.context,project:{...f.context.project,id:"foreign"}},f.input)).rejects.toThrow("another project");f.host.get=async()=>({id:"other",location:{directory:f.workspace}});await expect(guide.send(f.context,f.input)).rejects.toThrow("owned session");expect(f.prompts).toHaveLength(0)}finally{f.cleanup()}})
test("terminal runs reject new guidance; acknowledgement is separate from completion",async()=>{const f=fixture();try{const guide=new SessionGuidance(f.store,f.host,{supported:true});const row=await guide.send(f.context,{...f.input,delivery:"steer"});expect(()=>guide.acknowledge(f.context,{questID:"00000000000000000000000001",guidanceID:row.id})).toThrow("addressed worker");expect(guide.acknowledge({...f.context,sessionID:"worker"},{questID:"00000000000000000000000001",guidanceID:row.id}).state).toBe("acknowledged");expect(f.store.read("00000000000000000000000001")!.sessions[0].state).toBe("executing");f.store.apply("00000000000000000000000001","session-state",{callID:"run",state:"cancelled"});await expect(guide.send(f.context,{...f.input,text:"new guidance"})).rejects.toThrow("active");expect(f.prompts).toHaveLength(1)}finally{f.cleanup()}})
test("missing stable host receipt remains unknown",async()=>{const f=fixture();try{f.host.prompt=async()=>({id:"wrong"});expect((await new SessionGuidance(f.store,f.host,{supported:true}).send(f.context,f.input)).state).toBe("unknown")}finally{f.cleanup()}})

test("receipt for another session remains unknown and cancellation during host lookup sends nothing",async()=>{const f=fixture();try{f.host.prompt=async(i:any)=>({id:i.id,sessionID:"foreign"});const guide=new SessionGuidance(f.store,f.host,{supported:true});expect((await guide.send(f.context,f.input)).state).toBe("unknown");f.host.get=async()=>{f.store.apply("00000000000000000000000001","session-state",{callID:"run",state:"cancelled"});return{id:"worker",location:{directory:f.workspace}}};await expect(guide.send(f.context,{...f.input,text:"new evidence"})).rejects.toThrow("active");expect(f.prompts).toHaveLength(0)}finally{f.cleanup()}})
