import {test,expect} from "bun:test"
import {mkdtempSync,rmSync,writeFileSync} from "node:fs"
import {tmpdir} from "node:os"
import {join} from "node:path"
import {beginWorkflowRun,observeWorkflowRun,judgeWorkflowRun,readWorkflowOutcomes,reportWorkflowOutcomes,wilsonInterval,type WorkflowBegin,type WorkflowObservation} from "../usage/workflow-outcomes"
import {renderWorkflowReport} from "../usage/workflow-report"
const route={accountID:"a",providerID:"p",modelID:"m",reasoning:"high",harness:"opencode",version:"v1",serviceTier:"unknown"}
const begin=(id="r"):WorkflowBegin=>({runID:id,workflowID:"w",stepID:id,sessionID:id,route,taskTags:["coding"],startedAt:100,projectID:"p"})
const observation=(id="r"):WorkflowObservation=>({runID:id,observedAt:200,state:"completed",tokens:{input:10,cacheRead:20,cacheWrite:null,output:5,reasoning:null},reviewMilliseconds:null,integrationMilliseconds:0})
function fixture(fn:(file:string)=>void){const dir=mkdtempSync(join(tmpdir(),"workflow-outcome-"));try{fn(join(dir,"outcomes.json"))}finally{rmSync(dir,{recursive:true,force:true})}}
test("workflow records persist, retries are idempotent and observations never imply acceptance",()=>fixture(file=>{beginWorkflowRun(file,begin());beginWorkflowRun(file,begin());observeWorkflowRun(file,observation());observeWorkflowRun(file,observation());const data=readWorkflowOutcomes(file);expect(data.runs.length).toBe(1);expect(data.runs[0].judgment).toBeNull();const report=reportWorkflowOutcomes(file,{now:300});expect(report.matrix[0].acceptance).toBeNull();expect(report.matrix[0].tokens.cacheWrite.total).toBeNull();expect(report.matrix[0].tokens.cacheRead.total).toBe(20)}))
test("acceptance requires separate evidence, failures and immutable judgments remain visible",()=>fixture(file=>{beginWorkflowRun(file,begin());observeWorkflowRun(file,observation());const judge={runID:"r",judgedAt:250,accepted:true,reviewer:"human",firstPass:true,verification:[]} as const;expect(()=>judgeWorkflowRun(file,{...judge,verification:[]})).toThrow();const good={...judge,verification:[{command:"bun test",exitCode:0,artifact:"report.txt"}]};judgeWorkflowRun(file,good);judgeWorkflowRun(file,good);expect(()=>judgeWorkflowRun(file,{...good,accepted:false})).toThrow();expect(reportWorkflowOutcomes(file,{now:300}).matrix[0].accepted).toBe(1);expect(reportWorkflowOutcomes(file,{now:220}).matrix[0].unjudged).toBe(1)}))
test("heterogeneous routes are separate and sessions cannot be counted twice",()=>fixture(file=>{beginWorkflowRun(file,begin());expect(()=>beginWorkflowRun(file,{...begin("x"),sessionID:"r"})).toThrow();beginWorkflowRun(file,{...begin("child"),route:{...route,version:"v2"}});observeWorkflowRun(file,observation());observeWorkflowRun(file,observation("child"));const report=reportWorkflowOutcomes(file,{now:300});expect(report.matrix.length).toBe(2);expect(report.workflows[0].elapsedMilliseconds).toBe(100);expect(report.workflows[0].workerMilliseconds).toBe(200);expect(report.workflows[0].maxConcurrent).toBe(2);expect(reportWorkflowOutcomes(file,{now:300,projectID:"other"}).runs).toEqual([])}))
test("late explicit counters preserve execution time, cannot decrease or reopen",()=>fixture(file=>{beginWorkflowRun(file,begin());observeWorkflowRun(file,observation());const late={...observation(),observedAt:230,completedAt:200,tokens:{input:10,cacheRead:20,cacheWrite:3,output:5,reasoning:2}};observeWorkflowRun(file,late);expect(reportWorkflowOutcomes(file,{now:300}).workflows[0].elapsedMilliseconds).toBe(100);expect(()=>observeWorkflowRun(file,{...late,observedAt:240,tokens:{...late.tokens,input:1}})).toThrow();expect(()=>observeWorkflowRun(file,{...late,observedAt:240,state:"running",completedAt:undefined})).toThrow();expect(()=>beginWorkflowRun(file,{...begin("nan"),startedAt:NaN})).toThrow()}))
test("windows, confidence bounds, unknowns and HTML escaping",()=>fixture(file=>{beginWorkflowRun(file,{...begin(),workflowTitle:'<script>alert("x")</script>',taskTags:['<img src=x onerror=alert(1)>']});const report=reportWorkflowOutcomes(file,{now:300,days:7});const html=renderWorkflowReport(report);expect(html).not.toContain("<script>");expect(html).not.toContain("<img");expect(html).toContain("&lt;script&gt;");expect(html).toContain("unknown");expect(wilsonInterval(0,0)).toBeNull();expect(wilsonInterval(0,1)![0]).toBeGreaterThanOrEqual(0);expect(wilsonInterval(1,1)![1]).toBeLessThanOrEqual(1);expect(()=>wilsonInterval(2,1)).toThrow();expect(reportWorkflowOutcomes(file,{now:29*86400000,days:28}).runs.length).toBe(0)}))
test("failed and running observations remain distinct from quality judgments",()=>fixture(file=>{beginWorkflowRun(file,begin());observeWorkflowRun(file,{...observation(),state:"running",tokens:{input:10,cacheRead:0,cacheWrite:0,output:5,reasoning:0}});let row=reportWorkflowOutcomes(file,{now:210}).matrix[0];expect(row.tokenCoverage.completeRuns).toBe(0);expect(row.tokenCoverage.unsettledRuns).toBe(1);expect(()=>observeWorkflowRun(file,{...observation(),observedAt:150})).toThrow();observeWorkflowRun(file,{...observation(),state:"failed",observedAt:220});expect(()=>judgeWorkflowRun(file,{runID:"r",judgedAt:230,accepted:true,reviewer:"reviewer",firstPass:null,verification:[{command:"test",exitCode:0,artifact:"log"}]})).toThrow();judgeWorkflowRun(file,{runID:"r",judgedAt:230,accepted:false,reviewer:"reviewer",firstPass:false,verification:[]});row=reportWorkflowOutcomes(file,{now:300}).matrix[0];expect(row.rejected).toBe(1);expect(row.acceptance).toBe(0);expect(row.tokenCoverage.unknownRuns).toBe(1)}))
test("plan regimes and project workflows remain separate; corrupt records fail closed",()=>fixture(file=>{beginWorkflowRun(file,{...begin(),route:{...route,planRegime:"plan-a"}});beginWorkflowRun(file,{...begin("b"),projectID:"q",route:{...route,planRegime:"plan-b"}});const report=reportWorkflowOutcomes(file,{now:300});expect(report.matrix.length).toBe(2);expect(report.workflows.length).toBe(2);const data=readWorkflowOutcomes(file);delete (data.runs[0] as any).judgment;writeFileSync(file,JSON.stringify(data));expect(()=>readWorkflowOutcomes(file)).toThrow();writeFileSync(file,'null');expect(()=>readWorkflowOutcomes(file)).toThrow();expect(()=>beginWorkflowRun(file,{...begin("c"),route:{...route,planRegime:""}})).toThrow()}))
test("verified mixed-route work is not quality evidence for its first route",()=>fixture(file=>{beginWorkflowRun(file,begin());observeWorkflowRun(file,{...observation(),routeConsistent:false});judgeWorkflowRun(file,{runID:"r",judgedAt:250,accepted:true,reviewer:"review",firstPass:null,verification:[{command:"test",exitCode:0,artifact:"log"}]});const report=reportWorkflowOutcomes(file,{now:300});expect(report.runs[0].judgment?.accepted).toBe(true);expect(report.matrix[0].acceptance).toBeNull();expect(report.matrix[0].unattributedJudgments).toBe(1);expect(report.matrix[0].unjudged).toBe(0)}))
test("judgment remains immutable while late provider counters update",()=>fixture(file=>{beginWorkflowRun(file,begin());observeWorkflowRun(file,{...observation(),completedAt:200});const judgment={runID:"r",judgedAt:210,accepted:true,reviewer:"reviewer",firstPass:true,verification:[{command:"test",exitCode:0,artifact:"log"}]};judgeWorkflowRun(file,judgment);const late={...observation(),completedAt:200,observedAt:300,tokens:{input:10,cacheRead:20,cacheWrite:4,output:12,reasoning:2}};observeWorkflowRun(file,late);const saved=readWorkflowOutcomes(file).runs[0];expect(saved.judgment).toEqual(judgment);expect(saved.observation?.tokens.output).toBe(12);expect(reportWorkflowOutcomes(file,{now:310}).matrix[0].tokenCoverage.completeRuns).toBe(1);expect(()=>observeWorkflowRun(file,{...late,observedAt:320,reviewMilliseconds:4})).toThrow();expect(()=>observeWorkflowRun(file,{...late,observedAt:320,state:"running",completedAt:undefined})).toThrow();expect(()=>judgeWorkflowRun(file,{...judgment,reviewer:"different"})).toThrow();observeWorkflowRun(file,{...late,observedAt:320,routeConsistent:false});expect(reportWorkflowOutcomes(file,{now:330}).matrix[0].unattributedJudgments).toBe(1)}))
