export const QUEST_WEB_PATH = '/web'

/** The API credential stays in the fragment, so it is never sent in a URL or request log. */
export function questWebURL(baseURL: string, token: string) {
  return baseURL.replace(/\/$/, '') + QUEST_WEB_PATH + '#access_token=' + encodeURIComponent(token)
}

/** A dependency-free local surface served by the authenticated Quest API. */
export function questWebHTML() {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Quest Web</title><style>
:root{color-scheme:dark;font:15px/1.45 ui-sans-serif,system-ui,sans-serif;background:#0b0d10;color:#e8ebef}*{box-sizing:border-box}body{margin:0}header{position:sticky;top:0;z-index:2;padding:18px clamp(18px,4vw,52px);background:#0b0d10e8;border-bottom:1px solid #262b33;backdrop-filter:blur(12px)}h1{font-size:20px;margin:0}header p{margin:3px 0 0;color:#99a2ad}main{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:18px;padding:22px clamp(18px,4vw,52px)}section{min-width:0}.heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}h2{font-size:14px;letter-spacing:.08em;text-transform:uppercase;color:#aab3bd;margin:0}.stack{display:grid;gap:10px}.card{background:#14181e;border:1px solid #292f38;border-radius:12px;padding:14px 15px}.title{font-weight:650}.meta,.muted{color:#939daa;font-size:13px}.meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.pill{border:1px solid #343c47;border-radius:999px;padding:2px 8px}.bar{height:7px;background:#272e37;border-radius:99px;overflow:hidden;margin:10px 0 5px}.bar>i{display:block;height:100%;background:#7c9cff;border-radius:inherit}.error{border-color:#63323a;color:#ffb7c0}button{font:inherit;color:inherit;background:#20262e;border:1px solid #38414c;border-radius:8px;padding:6px 10px;cursor:pointer}button:hover{background:#29313b}@media(max-width:820px){main{grid-template-columns:1fr}}
</style></head><body><header><h1>Quest Web</h1><p>Quests and account usage in one local surface.</p></header><main><section><div class="heading"><h2>Quests</h2><button id="refresh" type="button">Refresh</button></div><div id="quests" class="stack"><div class="card muted">Loading…</div></div></section><section><div class="heading"><h2>Usage</h2></div><div id="usage" class="stack"><div class="card muted">Loading…</div></div></section></main><script>
const supplied=new URLSearchParams(location.hash.slice(1)).get('access_token');if(supplied)sessionStorage.setItem('quest-web-token',supplied);const token=supplied||sessionStorage.getItem('quest-web-token');history.replaceState(null,'',location.pathname);
const quests=document.querySelector('#quests'),usage=document.querySelector('#usage');
const node=(tag,className,text)=>{const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=String(text);return e};
const card=(title,meta=[])=>{const e=node('article','card');e.append(node('div','title',title));if(meta.length){const m=node('div','meta');for(const value of meta)m.append(node('span','pill',value));e.append(m)}return e};
const fail=(target,error)=>{target.replaceChildren(node('div','card error',error instanceof Error?error.message:String(error)))};
async function read(path){if(!token)throw Error('This Quest Web link has no access token.');const r=await fetch(path,{headers:{authorization:'Bearer '+token}});const data=await r.json();if(!r.ok)throw Error(data.message||('HTTP '+r.status));return data}
function renderQuests(data){quests.replaceChildren();const items=Array.isArray(data.items)?data.items:[];if(!items.length){quests.append(node('div','card muted','No active Quests.'));return}for(const q of items){const steps=Array.isArray(q.stages)?q.stages:[];const done=steps.filter(s=>s.status==='done').length;const state=q.state||q.status||'Saved';const e=card(q.title||'Untitled Quest',[state,steps.length?done+' of '+steps.length+' steps':'No steps']);if(q.description||q.objective)e.append(node('p','muted',q.description||q.objective));if(steps.length){const b=node('div','bar');const i=node('i');i.style.width=(done/steps.length*100)+'%';b.append(i);e.append(b)}const next=steps.find(s=>s.status!=='done');if(next)e.append(node('div','muted','Next: '+next.title));quests.append(e)}}
function renderUsage(data){usage.replaceChildren();const accounts=Array.isArray(data.accounts)?data.accounts:[];if(!accounts.length){usage.append(node('div','card muted','No account usage is available.'));return}for(const a of accounts){const e=card((a.provider||'Account')+(a.plan&&a.plan.name?' · '+a.plan.name:''),[a.state||'unknown',a.freshness&&a.freshness.stale?'stale':'current']);for(const w of a.windows||[]){const used=Number(w.usedPercent);const row=node('div');row.append(node('div','meta',(w.label||w.id)+' · '+(Number.isFinite(used)?used.toFixed(1)+'% used':'usage unknown')));if(Number.isFinite(used)){const b=node('div','bar');const i=node('i');i.style.width=Math.max(0,Math.min(100,used))+'%';b.append(i);row.append(b)}if(w.resetAt)row.append(node('div','muted','Resets '+new Date(w.resetAt).toLocaleString()));e.append(row)}usage.append(e)}}
async function load(){try{const [q,u]=await Promise.all([read('/api/web/quests'),read('/api/web/usage')]);renderQuests(q);renderUsage(u)}catch(error){fail(quests,error);fail(usage,error)}}document.querySelector('#refresh').addEventListener('click',load);load();
</script></body></html>`
}
