import type { UsageExperience } from "./experience"

const escape = (value: unknown) => String(value??"unknown").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!))
/** Standalone accessible report, with no scripts, network resources or embedded sample data. */
export function renderUsageExperience(quota: UsageExperience, activity: UsageExperience = quota): string {
  if(quota.accountID!==activity.accountID||quota.timeZone!==activity.timeZone) throw Error("Report projections must share account and timezone")
  const points=quota.timeline?.items??[],requests=activity.requests?.items??[]
  const times=[...points.map(p=>p.at),...requests.flatMap(r=>[r.startedAt,r.at])]
  const from=times.length?Math.min(...times):quota.at,to=times.length?Math.max(...times):quota.at
  const span=Math.max(1,to-from),x=(at:number)=>64+(at-from)/span*640
  const date=(at:number|null)=>at===null?"unknown":new Intl.DateTimeFormat("en",{timeZone:quota.timeZone,year:"numeric",month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23",timeZoneName:"short"}).format(at)
  const tick=(at:number)=>new Intl.DateTimeFormat("en",{timeZone:quota.timeZone,month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23",timeZoneName:"short"}).format(at)
  const axes=(max:number,unit:string)=>[0,max/2,max].map(v=>`<line class="grid" x1="64" x2="704" y1="${200-v/max*150}" y2="${200-v/max*150}"/><text x="56" y="${204-v/max*150}" text-anchor="end">${escape(Number(v.toPrecision(4)))}</text>`).join("")+`<text x="64" y="24">${escape(unit)}</text>`+[0,.5,1].map((f,i)=>`<text x="${64+640*f}" y="226" text-anchor="${i===0?"start":i===2?"end":"middle"}">${escape(tick(from+span*f))}</text>`).join("")
  const mark=(at:number,value:number,max:number,label:string)=>`<g tabindex="0" role="img" aria-label="${escape(label)}"><title>${escape(label)}</title><circle cx="${x(at)}" cy="${200-value/max*150}" r="4"/><text class="tip" x="64" y="248">${escape(label)}</text></g>`
  const pageNote=(p:UsageExperience["timeline"]|UsageExperience["requests"])=>p?`Showing ${p.items.length} of ${p.total} records (offset ${p.offset}${p.nextOffset===null?"; end of page range":`; next offset ${p.nextOffset}`}).`:"No detail page supplied. Request the timeline or requests view to inspect data."
  const quotaRows=points.map(p=>`<tr><th scope="row">${escape(date(p.at))}</th><td>${p.usedPoints}</td><td>${escape(p.precisionPoints)}</td><td>${escape(p.reportingDelayMilliseconds)}</td><td>${p.breakBefore?"Start / gap / discontinuity":"Observation"}</td></tr>`).join("")
  const requestRows=requests.map(r=>`<tr><th scope="row">${escape(date(r.at))}</th><td>${escape(r.modelID)}</td><td>${escape(r.state)}</td><td>${escape(r.inputTokens)}</td><td>${escape(r.cacheReadTokens)}</td><td>${escape(r.outputIncludingReasoning)}</td><td>${escape(r.id)}</td></tr>`).join("")
  const output=requests.filter(r=>r.state!=="running"&&r.outputIncludingReasoning!==null),maximum=Math.max(1,...output.map(r=>r.outputIncludingReasoning!))
  const policy=quota.decision.policyTarget,rate=quota.decision.measuredQuotaRate
  const policyText=policy?`Authorized deadline ${date(policy.deadlineAt)}, reserve ${policy.reservePoints} points. Required wall-clock average ${policy.requiredPointsPerMinute===null?"unknown":(policy.requiredPointsPerMinute*60).toPrecision(4)} points/hour; this is a policy target, not predicted activity.`:"No authorized pacing target."
  const rateText=rate.pointsPerMinute===null?"Recent meter rate unavailable.":`Recent observed meter rate ${(rate.pointsPerMinute*60).toPrecision(4)} points/hour over ${date(rate.interval?.from??null)} → ${date(rate.interval?.to??null)}. Not a future schedule or prediction.`
  const gaps=quota.history.gaps.items.filter(g=>g.to>=from&&g.from<=to).map(g=>`<rect class="gap" x="${x(Math.max(from,g.from))}" y="40" width="${(Math.min(to,g.to)-Math.max(from,g.from))/span*640}" height="160"><title>Observation gap: ${escape(date(g.from))} to ${escape(date(g.to))}</title></rect>`).join("")
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Usage evidence — ${escape(quota.label)}</title><style>
  :root{color-scheme:light dark;--bg:#fff;--fg:#192434;--muted:#45556c;--line:#c5cdd8;--accent:#075ac2;--gap:#eee8db}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.55 system-ui,sans-serif}main{max-width:1000px;margin:auto;padding:24px}h1{font-size:1.8rem}h2{font-size:1.25rem;margin-top:2rem}p{max-width:85ch}small,.note{color:var(--muted)}figure{margin:1rem 0}figcaption{font-weight:600}svg{display:block;width:100%;min-width:560px;height:auto}svg text{fill:var(--fg);font:12px system-ui}circle{fill:var(--accent);stroke:var(--bg);stroke-width:1.5}.grid{stroke:var(--line)}.gap{fill:var(--gap)}.tip{display:none}g:hover .tip,g:focus .tip{display:block}g:focus circle{stroke:var(--fg);stroke-width:4}.scroll{overflow:auto;border:1px solid var(--line);border-radius:6px}a{color:var(--accent)}:focus-visible{outline:3px solid var(--accent);outline-offset:3px}table{border-collapse:collapse;width:100%;font-size:.9rem}th,td{padding:10px;text-align:left;border-bottom:1px solid var(--line);overflow-wrap:anywhere}th{font-weight:600}details{margin:1rem 0}summary{cursor:pointer;padding:8px}dl{display:grid;grid-template-columns:minmax(130px,1fr) 3fr;gap:8px}dt{font-weight:600}dd{margin:0;overflow-wrap:anywhere}.decision{border-left:4px solid var(--accent);padding-left:16px}@media(prefers-color-scheme:dark){:root{--bg:#111923;--fg:#edf2f8;--muted:#b8c7db;--line:#4b596c;--accent:#8dc2ff;--gap:#363126}}@media(max-width:600px){main{padding:14px}h1{font-size:1.5rem}dl{display:block}dd{margin-bottom:12px}.scroll{margin-right:0}}@media print{details>*{display:block}.scroll{overflow:visible}svg{min-width:0}}
  </style></head><body><main><h1>What the usage evidence says</h1><p>${escape(quota.summary)}</p><p class="note">Account ${escape(quota.accountID)} · ${escape(quota.label)} · ${escape(quota.timeZone)}. Report assembled ${escape(date(quota.at))}.</p>
  <section class="decision" aria-labelledby="decision"><h2 id="decision">Next safe action: ${escape(quota.decision.nextAction)}</h2><p>${escape(quota.decision.reason)}</p><p>${quota.decision.desiredSlots} desired slots; launch ownership unknown. ${escape(quota.decision.admission)}.</p><p>${escape(policyText)}</p><p>${escape(rateText)}</p></section>
  <h2>Account meter and request activity</h2><p>Both graphs use the same elapsed time axis: ${escape(date(from))} → ${escape(date(to))}. Dots are observed values; space between them is not interpolated. Scroll horizontally on narrow screens; focus a dot for its value or open its data table.</p>
  <figure><figcaption>Account quota — used percentage points of this pool</figcaption><p>Reset epoch ${escape(date(quota.history.selectedEpoch.resetAt))}; regime ${escape(quota.history.selectedEpoch.regime)}${quota.history.current?" (current)":" (historical)"}. ${escape(pageNote(quota.timeline))}</p><div class="scroll" tabindex="0" role="region" aria-label="Quota history, horizontal scroll"><svg viewBox="0 0 768 268" role="group" aria-label="Observed used quota points, never attributed to this session">${gaps}${axes(100,"Used points (0–100)")}${points.map(p=>mark(p.at,p.usedPoints,100,`${tick(p.at)} · ${p.usedPoints} used points`)).join("")}</svg></div><p class="note">${quota.history.gapCount} gaps exceed ${quota.history.gapThresholdMilliseconds/60000} minutes; shaded gaps are missing observations, not idle time. ${quota.history.conflictingSamples} conflicting samples; ${quota.history.decreases} decreases. Gap annotations show up to ${quota.history.gaps.limit}; dots are never joined.</p></figure>
  <details><summary>Quota data and source precision</summary><div class="scroll" tabindex="0" role="region" aria-label="Quota data table"><table><caption>Observed meter values; unknown precision and delay remain unknown</caption><thead><tr><th scope="col">Observed time</th><th scope="col">Used points</th><th scope="col">Precision (points)</th><th scope="col">Reporting delay (ms)</th><th scope="col">Continuity</th></tr></thead><tbody>${quotaRows}</tbody></table></div></details>
  <figure><figcaption>Measured request output — tokens, independent of quota</figcaption><p>Source ${escape(activity.activity.source)}; recorded account bindings only. ${escape(pageNote(activity.requests))}</p><div class="scroll" tabindex="0" role="region" aria-label="Request token history, horizontal scroll"><svg viewBox="0 0 768 268" role="group" aria-label="Terminal request output including reasoning tokens">${axes(maximum,"Output including reasoning (tokens)")}${output.map(r=>mark(r.at,r.outputIncludingReasoning!,maximum,`${tick(r.at)} · ${r.outputIncludingReasoning} tokens · ${r.state}`)).join("")}</svg></div><p class="note">${activity.activity.terminalRequests} terminal / ${activity.activity.runningRequests} running records. Running and unknown counters are omitted from the token plot, not plotted as zero. ${escape(activity.activity.coverage)}</p></figure>
  <details><summary>Request data, status and token categories</summary><div class="scroll" tabindex="0" role="region" aria-label="Request data table"><table><caption>Exclusive uncached input, cached input and combined output tokens</caption><thead><tr><th scope="col">Counter time</th><th scope="col">Model</th><th scope="col">Status</th><th scope="col">Uncached input</th><th scope="col">Cached input</th><th scope="col">Output + reasoning</th><th scope="col">Record</th></tr></thead><tbody>${requestRows}</tbody></table></div></details>
  <h2>How much evidence is available?</h2><dl><dt>Quota history</dt><dd>${quota.history.availableSamples} unique records in ${quota.history.epochCount} separate reset epochs; ${quota.history.selectedSamples} in the selected interval. ${quota.history.duplicateSamples} duplicates removed.</dd><dt>Meter freshness</dt><dd>Observed ${escape(date(quota.observedQuota.observedAt))}; age ${escape(quota.observedQuota.ageMilliseconds)} ms; ${escape(quota.observedQuota.state)}. ${escape(quota.observedQuota.reason??"")}</dd><dt>Collection</dt><dd>Collector ${escape(date(quota.sources.collectorAt))}; host scan ${escape(date(quota.sources.hostScanAt))}; coverage starts ${escape(date(quota.sources.coverageFrom))}. ${quota.sources.diagnosticCount} source diagnostics.</dd><dt>Missing bindings</dt><dd>${activity.activity.missingAccountBindings} request records. ${escape(activity.activity.missingBindingScope)}.</dd><dt>Counter gaps</dt><dd>${activity.activity.counterGapCount}; these may belong to accounts whose bindings are missing.</dd><dt>Activity horizon</dt><dd>${escape(date(activity.activity.range?.from??null))} → ${escape(date(activity.activity.range?.to??null))}; ${activity.activity.activeDays} observed days; ${activity.activity.activeMilliseconds} measured terminal-request milliseconds (overlap removed within this source).</dd></dl>
  <p>Largest quota observation gap: ${quota.history.largestGap?`${escape(date(quota.history.largestGap.from))} → ${escape(date(quota.history.largestGap.to))} (${quota.history.largestGap.milliseconds} ms)`:"none in the selected evidence interval"}.</p><h2>What cannot be predicted</h2><p>${escape(activity.expectedActivity.reason)}. No recurring work schedule or session allowance charge is inferred. A flat meter means no reported movement, even while requests are active.</p><p>${escape(activity.activity.routeReceiptAuthority)}. ${activity.activity.excludedUnboundSourceRecords} unbound ${escape(activity.activity.source)} records excluded from this account's activity.</p><p>Evidence needed before an activity estimate can be evaluated:</p><ul>${activity.expectedActivity.neededEvidence.map(s=>`<li>${escape(s)}</li>`).join("")}</ul><ul>${quota.limitations.map(s=>`<li>${escape(s)}</li>`).join("")}</ul></main></body></html>`
}
