import {existsSync,readFileSync,writeFileSync,renameSync,mkdirSync} from "node:fs"
import {dirname} from "node:path"
import {createHash} from "node:crypto"
import {acquireLock} from "../quest/locking"

export type WorkflowRoute={planRegime?:string;accountID:string;providerID:string;modelID:string;reasoning:string;harness:string;version:string;serviceTier:string}
export type WorkflowTokens={input:number|null;cacheRead:number|null;cacheWrite:number|null;output:number|null;reasoning:number|null}
export type WorkflowBegin={projectID?:string;workflowTitle?:string;runID:string;workflowID:string;stepID:string;sessionID:string;route:WorkflowRoute;taskTags:string[];startedAt:number}
export type WorkflowObservation={routeConsistent?:boolean;runID:string;observedAt:number;completedAt?:number;state:"running"|"completed"|"failed"|"cancelled";tokens:WorkflowTokens;reviewMilliseconds:number|null;integrationMilliseconds:number|null}
export type WorkflowJudgment={runID:string;judgedAt:number;accepted:boolean;reviewer:string;firstPass:boolean|null;verification:{command:string;exitCode:number;artifact:string}[]}
export type WorkflowRun=WorkflowBegin & {observation:WorkflowObservation|null;judgment:WorkflowJudgment|null}
export type WorkflowStore={version:1;runs:WorkflowRun[]}
const tokenFields=["input","cacheRead","cacheWrite","output","reasoning"] as const
const text=(x:unknown)=>typeof x==="string"&&x.trim().length>0&&x.length<=2048
const time=(x:unknown)=>typeof x==="number"&&Number.isFinite(x)&&x>=0&&x<=8640000000000000
const canonical=(x:unknown):string=>JSON.stringify(x,(_k,v)=>v&&typeof v==="object"&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v)
function validBegin(r:WorkflowBegin){if(!r||(r.projectID!==undefined&&!text(r.projectID))||(r.workflowTitle!==undefined&&!text(r.workflowTitle))||![r.runID,r.workflowID,r.stepID,r.sessionID].every(text)||!r.route||(r.route.planRegime!==undefined&&!text(r.route.planRegime))||!["accountID","providerID","modelID","reasoning","harness","version","serviceTier"].every(k=>text(r.route[k as keyof WorkflowRoute]))||!Array.isArray(r.taskTags)||!r.taskTags.length||r.taskTags.some(t=>!text(t))||new Set(r.taskTags).size!==r.taskTags.length||!time(r.startedAt))throw Error("Invalid workflow identity or start time")}
function validObservation(o:WorkflowObservation,r:WorkflowBegin){if(!o||(o.routeConsistent!==undefined&&typeof o.routeConsistent!=="boolean")||(o.completedAt!==undefined&&(!time(o.completedAt)||o.completedAt<r.startedAt||o.completedAt>o.observedAt||o.state==="running"))||o.runID!==r.runID||!time(o.observedAt)||o.observedAt<r.startedAt||!["running","completed","failed","cancelled"].includes(o.state)||!o.tokens||tokenFields.some(k=>o.tokens[k]!==null&&(!Number.isSafeInteger(o.tokens[k])||o.tokens[k]!<0))||[o.reviewMilliseconds,o.integrationMilliseconds].some(v=>v!==null&&!time(v)))throw Error("Invalid workflow observation")}
function validJudgment(j:WorkflowJudgment,r:WorkflowRun){if(!j||j.runID!==r.runID||!r.observation||r.observation.state==="running"||!time(j.judgedAt)||j.judgedAt<(r.observation.completedAt??r.observation.observedAt)||typeof j.accepted!=="boolean"||!text(j.reviewer)||![true,false,null].includes(j.firstPass)||!Array.isArray(j.verification)||j.verification.some(v=>!text(v.command)||!text(v.artifact)||!Number.isInteger(v.exitCode)))throw Error("Invalid workflow judgment")
 if(j.accepted&&(r.observation.state!=="completed"||!j.verification.length||j.verification.some(v=>v.exitCode!==0)))throw Error("Acceptance requires completed work and successful verification evidence")
 if(!j.accepted&&j.firstPass===true)throw Error("Rejected work cannot be first-pass accepted")
}
export function readWorkflowOutcomes(file:string):WorkflowStore{
 if(!existsSync(file))return {version:1,runs:[]}
 const data=JSON.parse(readFileSync(file,"utf8")) as WorkflowStore
 if(!data||data.version!==1||!Array.isArray(data.runs))throw Error("Unreadable workflow outcomes")
 const ids=new Set<string>(),sessions=new Set<string>()
 for(const r of data.runs){validBegin(r);if(r.observation!==null&&(typeof r.observation!=="object"||!r.observation)||r.judgment!==null&&(typeof r.judgment!=="object"||!r.judgment))throw Error("Missing or invalid observation/judgment state");if(ids.has(r.runID)||sessions.has(r.sessionID))throw Error("Duplicate workflow run or session");ids.add(r.runID);sessions.add(r.sessionID);if(r.observation)validObservation(r.observation,r);if(r.judgment)validJudgment(r.judgment,r)}return data
}
function mutate<T>(file:string,fn:(data:WorkflowStore)=>T):T{
 const lock=acquireLock(dirname(file),"workflow-outcomes-"+createHash("sha256").update(file).digest("hex").slice(0,16))
 try{const data=readWorkflowOutcomes(file),result=fn(data);mkdirSync(dirname(file),{recursive:true});const tmp=file+"."+process.pid+".tmp";writeFileSync(tmp,JSON.stringify(data),{mode:0o600});renameSync(tmp,file);return result}finally{lock.release()}
}
/** A session belongs to exactly one run. Parent/child sessions must each be recorded explicitly. */
export function beginWorkflowRun(file:string,input:WorkflowBegin):WorkflowRun{
 validBegin(input);return mutate(file,data=>{const old=data.runs.find(r=>r.runID===input.runID);if(old){const {observation,judgment,...identity}=old;if(canonical(identity)!==canonical(input))throw Error("Run identity is immutable");return old}if(data.runs.some(r=>r.sessionID===input.sessionID))throw Error("Session already attributed to another run");const run={...input,observation:null,judgment:null};data.runs.push(run);return run})
}
/** Cumulative counters are observed, never inferred. Late terminal updates preserve completedAt; judgments freeze verdicts and review effort, while late numeric capture remains observable. Null counters remain unknown in every aggregate. */
export function observeWorkflowRun(file:string,input:WorkflowObservation):WorkflowRun{
 return mutate(file,data=>{const r=data.runs.find(r=>r.runID===input.runID);if(!r)throw Error("Unknown workflow run");validObservation(input,r);const old=r.observation;if(old){if(canonical(old)===canonical(input))return r;if(old.routeConsistent===false&&input.routeConsistent!==false)throw Error("Mixed route attribution cannot be upgraded");if(input.observedAt<=old.observedAt)throw Error("Observation is stale");if(r.judgment&&input.routeConsistent!==old.routeConsistent&&input.routeConsistent!==false)throw Error("Judged route attribution can only be downgraded");if(r.judgment&&(input.reviewMilliseconds!==old.reviewMilliseconds||input.integrationMilliseconds!==old.integrationMilliseconds))throw Error("Judged review and integration effort are immutable");if(old.state!=="running"&&(input.state!==old.state||input.completedAt!==(old.completedAt??old.observedAt)))throw Error("Terminal state and completion time are immutable");if(tokenFields.some(k=>old.tokens[k]!==null&&input.tokens[k]!==null&&input.tokens[k]!<old.tokens[k]!))throw Error("Cumulative counters cannot decrease");if(["reviewMilliseconds","integrationMilliseconds"].some(k=>old[k as "reviewMilliseconds"]!==null&&input[k as "reviewMilliseconds"]!==null&&input[k as "reviewMilliseconds"]!<old[k as "reviewMilliseconds"]!))throw Error("Cumulative effort cannot decrease")}
 r.observation=input;return r})
}
export function judgeWorkflowRun(file:string,input:WorkflowJudgment):WorkflowRun{
 return mutate(file,data=>{const r=data.runs.find(r=>r.runID===input.runID);if(!r)throw Error("Unknown workflow run");validJudgment(input,r);if(r.judgment&&canonical(r.judgment)!==canonical(input))throw Error("Judgment already recorded");r.judgment=input;return r})
}
export function workflowRouteKey(route:WorkflowRoute){return canonical(route)}
export function wilsonInterval(successes:number,total:number):[number,number]|null{
 if(!Number.isInteger(total)||!Number.isInteger(successes)||total<0||successes<0||successes>total)throw Error("Invalid interval sample")
 if(!total)return null;const z=1.959963984540054,p=successes/total,d=1+z*z/total,center=(p+z*z/(2*total))/d,half=z*Math.sqrt(p*(1-p)/total+z*z/(4*total*total))/d;return [Math.max(0,center-half),Math.min(1,center+half)]
}
const sumKnown=(values:(number|null)[])=>({known:values.reduce<number>((a,b)=>a+(b??0),0),unknown:values.filter(v=>v===null).length,total:values.every(v=>v!==null)?values.reduce<number>((a,b)=>a+b!,0):null})
export function reportWorkflowOutcomes(file:string,options:{now?:number;days?:7|28;projectID?:string}={}){
 const now=options.now??Date.now(),days=options.days??28;if(!time(now)||![7,28].includes(days))throw Error("Invalid report window");const from=now-days*86400000
 const all=readWorkflowOutcomes(file).runs.filter(r=>r.startedAt<=now&&(!options.projectID||r.projectID===options.projectID)),runs=all.filter(r=>r.startedAt>=from).map(r=>({...r,observation:r.observation&&r.observation.observedAt<=now?r.observation:null,judgment:r.judgment&&r.judgment.judgedAt<=now?r.judgment:null}))
 const keys=[...new Set(runs.flatMap(r=>r.taskTags.map(tag=>JSON.stringify([workflowRouteKey(r.route),tag]))))]
 const matrix=keys.map(key=>{const [routeKey,taskTag]=JSON.parse(key),items=runs.filter(r=>workflowRouteKey(r.route)===routeKey&&r.taskTags.includes(taskTag)),judged=items.filter(r=>r.judgment!==null&&r.observation?.routeConsistent!==false),accepted=judged.filter(r=>r.judgment!.accepted).length,first=judged.filter(r=>r.judgment!.firstPass!==null);return {route:items[0].route,taskTag,samples:items.length,judged:judged.length,accepted,rejected:judged.length-accepted,unjudged:items.filter(r=>r.judgment===null).length,unattributedJudgments:items.filter(r=>r.judgment!==null&&r.observation?.routeConsistent===false).length,acceptance:judged.length?accepted/judged.length:null,acceptanceInterval:wilsonInterval(accepted,judged.length),tokenCoverage:{completeRuns:items.filter(r=>r.observation&&r.observation.state!=="running"&&tokenFields.every(k=>r.observation!.tokens[k]!==null)).length,unsettledRuns:items.filter(r=>!r.observation||r.observation.state==="running").length,unknownRuns:items.filter(r=>!r.observation||tokenFields.some(k=>r.observation!.tokens[k]===null)).length},firstPassKnown:first.length,firstPassAccepted:first.filter(r=>r.judgment!.accepted&&r.judgment!.firstPass).length,tokens:Object.fromEntries(tokenFields.map(k=>[k,sumKnown(items.map(r=>r.observation?.tokens[k]??null))]))}})
 const workflows=[...new Set(runs.map(r=>JSON.stringify([r.projectID??null,r.workflowID])))].map(workflowKey=>{const [projectID,workflowID]=JSON.parse(workflowKey),items=runs.filter(r=>r.workflowID===workflowID&&(r.projectID??null)===projectID),startedAt=Math.min(...items.map(r=>r.startedAt)),terminal=items.every(r=>r.observation&&r.observation.state!=="running"),completedAt=terminal?Math.max(...items.map(r=>(r.observation!.completedAt??r.observation!.observedAt))):null
 const events=items.filter(r=>(r.observation&&r.observation.state!=="running"?(r.observation.completedAt??r.observation.observedAt):now)>r.startedAt).flatMap(r=>[{at:r.startedAt,delta:1},{at:r.observation&&r.observation.state!=="running"?(r.observation.completedAt??r.observation.observedAt):now,delta:-1}]).sort((a,b)=>a.at-b.at||a.delta-b.delta);let active=0,maxConcurrent=0;for(const event of events){active+=event.delta;maxConcurrent=Math.max(maxConcurrent,active)}
 return {projectID,workflowID,startedAt,completedAt,elapsedMilliseconds:(completedAt??now)-startedAt,workerMilliseconds:items.reduce((n,r)=>n+(r.observation&&r.observation.state!=="running"?(r.observation.completedAt??r.observation.observedAt):now)-r.startedAt,0),maxConcurrent,runIDs:items.map(r=>r.runID),partialWindow:all.some(r=>r.workflowID===workflowID&&(r.projectID??null)===projectID&&r.startedAt<from),reviewMilliseconds:sumKnown(items.map(r=>r.observation?.reviewMilliseconds??null)),integrationMilliseconds:sumKnown(items.map(r=>r.observation?.integrationMilliseconds??null))}})
 return {now,from,days,runs,matrix,workflows,note:"Observed runs started in this window. Task tags overlap; do not sum matrix rows. Unjudged work and judgments with mixed routes are excluded from route acceptance denominators. Verified acceptance does not imply complete token coverage or eligibility for model routing. Tokens are disjoint input, cache reads, cache writes, output and reasoning counters; null is unknown. Worker time is summed run duration, not CPU time. Concurrency observations do not establish causal speedup. Routes retain account, harness and version identity; no model ranking is inferred."}
}
export type WorkflowReport=ReturnType<typeof reportWorkflowOutcomes>
