import type {WorkflowReport} from "./workflow-outcomes"
const escape=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!))
const number=(value:number|null)=>value===null?"unknown":value.toLocaleString("en-US",{maximumFractionDigits:1})
/** Standalone export; embeds no scripts, network dependencies or invented series. */
export function renderWorkflowReport(report:WorkflowReport):string{
 const matrix=report.matrix.map(row=>`<tr><td>${escape(row.route.modelID)}<br><small>${escape(JSON.stringify(row.route))}</small></td><td>${escape(row.taskTag)}</td><td>${row.samples} / ${row.judged} / ${row.unjudged}<br>${row.unattributedJudgments} mixed-route judgments excluded</td><td>${row.acceptance===null?"unjudged":`${number(row.acceptance*100)}% <meter min="0" max="1" value="${row.acceptance}"></meter><br>95% interval ${row.acceptanceInterval!.map(v=>number(v*100)+"%").join(" – ")}`}</td><td>${row.firstPassAccepted} / ${row.firstPassKnown} known</td><td>${row.tokenCoverage.completeRuns} settled complete; ${row.tokenCoverage.unsettledRuns} unsettled; ${row.tokenCoverage.unknownRuns} unknown<br>${Object.entries(row.tokens).map(([key,value])=>`${escape(key)}: ${number(value.total)} (${number(value.known)} known; ${value.unknown} unknown runs)`).join("<br>")}</td></tr>`).join("")
 const timeline=report.workflows.map(w=>{const runs=report.runs.filter(r=>w.runIDs.includes(r.runID)),end=w.completedAt??report.now,span=Math.max(1,end-w.startedAt);return `<section><h3>${escape(runs[0]?.workflowTitle??w.workflowID)}</h3><p>Elapsed ${number(w.elapsedMilliseconds/1000)}s; summed worker time ${number(w.workerMilliseconds/1000)}s; peak overlapping runs ${w.maxConcurrent}${w.partialWindow?"; partial window":""}.</p>${runs.map(r=>{const finish=r.observation&&r.observation.state!=="running"?(r.observation.completedAt??r.observation.observedAt):report.now,left=(r.startedAt-w.startedAt)/span*100,width=Math.max(0,(finish-r.startedAt)/span*100);return `<div class="timeline"><span>${escape(r.stepID)} · ${escape(r.route.modelID)} · ${escape(r.observation?.state??"unobserved")}</span><div class="track"><div class="bar" style="margin-left:${left}%;width:${width}%"></div></div></div>`}).join("")}<p>Review: ${number(w.reviewMilliseconds.total)} ms; integration: ${number(w.integrationMilliseconds.total)} ms. Unknown effort is not zero.</p></section>`}).join("")
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Workflow evidence</title><style>body{font:16px system-ui;background:#101721;color:#edf2fa;margin:32px}table{border-collapse:collapse;width:100%}td,th{text-align:left;vertical-align:top;border-bottom:1px solid #526073;padding:12px}small{display:block;max-width:28em;overflow-wrap:anywhere;color:#abbcd1}section{margin:28px 0;padding:16px;background:#192432}.timeline{margin:12px 0}.track{height:14px;background:#293a50;margin-top:6px}.bar{height:14px;background:#74c8e8}meter{width:100px}p{max-width:100ch}</style><h1>Workflow evidence · ${report.days} days</h1><p>${escape(report.note)}</p><p>As of ${escape(new Date(report.now).toISOString())}. ${report.runs.length} observed runs. These observational cohorts do not establish which model is best or how much parallelism caused speedup.</p><h2>Model and task evidence</h2><table><thead><tr><th>Exact route</th><th>Task</th><th>Samples / judged / unjudged</th><th>Acceptance</th><th>First pass</th><th>Tokens</th></tr></thead><tbody>${matrix||'<tr><td colspan="6">No observed runs in this window.</td></tr>'}</tbody></table><h2>Workflow timelines and observed concurrency</h2>${timeline||'<p>No timelines available.</p>'}</html>`
}
