import { randomBytes } from "node:crypto"
import { readAllQuests } from "../quest/index"
import type { Quest } from "../quest/types"
import { QuestStore } from "../quest/store"
import { questRoot } from "../quest/root"
import { requestFingerprint } from "../quest/privacy"
import { getPapercut, queryPapercuts, recordPapercutEvidence, type Papercut } from "../plugins-active/papercut-memory"
export type PapercutFilter = { repo?: string; family?: string; errorSignature?: string; state?: "unresolved" | "resolved"; confidence?: number; sinceDays?: number; limit?: number }
export type PapercutScreen = { rows: Array<{ id: string; family: string; state: string; confidence: number; occurrences: number; signature: string; command: string; lastSeen: string }>; filters: PapercutFilter; selected?: ReturnType<typeof papercutDetail> }
export function papercutDetail(row: Papercut | undefined) { if (!row) return undefined; return { id: row.id, state: row.state, confidence: row.confidence, repo: row.repo, family: row.family, errorSignature: row.errorSignature, command: row.command, failure: row.failure, solutions: row.solutions, suggestedRemediation: row.suggestedRemediation, evidence: row.evidence || [] } }
export function renderPapercutScreen(filters: PapercutFilter = {}, file?: string, selectedID?: string): PapercutScreen { const rows = queryPapercuts(filters, file); return { filters, rows: rows.map(r => ({ id: r.id, family: r.family, state: r.state, confidence: r.confidence, occurrences: r.occurrences, signature: r.errorSignature, command: r.command, lastSeen: r.lastSeen })), selected: selectedID ? papercutDetail(getPapercut(selectedID, file)) : undefined } }
export function renderPapercutText(screen: PapercutScreen) { const header = `Papercuts: ${screen.rows.length} | state=${screen.filters.state || "all"} | family=${screen.filters.family || "all"}`; return [header, ...screen.rows.map(r => `${r.id} ${r.state} ${r.family} confidence=${r.confidence.toFixed(2)} occurrences=${r.occurrences} ${r.signature} :: ${r.command}`), screen.selected ? `\nDetail ${screen.selected.id}\nState: ${screen.selected.state}\nConfidence: ${screen.selected.confidence}\nRepo: ${screen.selected.repo}\nFamily: ${screen.selected.family}\nError signature: ${screen.selected.errorSignature}\nFailure: ${screen.selected.failure.excerpt || screen.selected.failure.status}\nSuggested remediation: ${screen.selected.suggestedRemediation || "none"}\nKnown solutions:\n${screen.selected.solutions.map(s => `- ${s.command} [${s.evidence}]`).join("\n") || "- none"}\nReplay evidence: ${screen.selected.evidence.length ? screen.selected.evidence.map(e => `${e.outcome}: ${e.detail}`).join("; ") : "none"}` : ""].filter(Boolean).join("\n") }
export type ReplayResult = { ok: boolean; status: "declined" | "unavailable" | "applied" | "failed"; command: string; message: string }
export async function replayPapercut(id: string, options: { solutionIndex?: number; confirm?: string; file?: string; allowExecution?: boolean; execute?: (command: string, cwd: string, shell: string) => Promise<unknown> | unknown } = {}): Promise<ReplayResult> { const row = getPapercut(id, options.file), solution = row?.solutions[options.solutionIndex || 0]; if (!row || !solution) return { ok: false, status: "unavailable", command: "", message: "Papercut or known solution was not found." }; if (options.confirm !== "APPLY") { recordPapercutEvidence(id, "declined", "Replay was not explicitly confirmed.", options.file); return { ok: false, status: "declined", command: solution.command, message: "Replay declined; no command was executed." } }; if (!options.allowExecution || !options.execute) { recordPapercutEvidence(id, "unavailable", "No explicitly trusted replay executor was provided.", options.file); return { ok: false, status: "unavailable", command: solution.command, message: "Replay unavailable; fail-closed without a trusted executor." } }; try { await options.execute(solution.command, row.cwd, row.shell); recordPapercutEvidence(id, "applied", "Trusted executor reported success.", options.file); return { ok: true, status: "applied", command: solution.command, message: "Replay applied and evidence recorded." } } catch (error) { recordPapercutEvidence(id, "failed", String(error), options.file); return { ok: false, status: "failed", command: solution.command, message: "Replay failed; failure evidence recorded." } } }
function questID() { const alphabet = "0123456789abcdefghjkmnpqrstvwxyz"; return [...randomBytes(26)].map(b => alphabet[b % alphabet.length]).join("") }
export function createPapercutFollowup(id: string, projectRoot = questRoot(), file?: string): Quest | undefined { const row = getPapercut(id, file); if (!row || row.state !== "unresolved") return undefined; const existing = readAllQuests(projectRoot).map(x => x.quest).find(q => q?.extensions?.papercutID === id && q.state !== "Archived" && q.state !== "Complete"); if (existing) return existing; const title = `Resolve papercut ${row.errorSignature}`; return new QuestStore(projectRoot).create({ id: questID(), title, objective: `Resolve ${row.errorSignature} in ${row.repo}; inspect the recorded failure before acting.`, kind: "investigation", priority: "normal", requestFingerprint: requestFingerprint({ papercutID: id, signature: row.errorSignature }), extensions: { papercutID: id, papercutRepo: row.repo, papercutFamily: row.family } }) }
