/** Offline transcript reader. It never invokes a command found in a transcript. */
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { Database } from "bun:sqlite"
import { formatPapercuts, queryPapercuts, recordShell } from "../plugins-active/papercut-memory"

type ReplayEvent = { sessionID: string; id: string; tool: string; input: { command: string; cwd?: string; shell?: string }; output?: unknown; at?: number }
const DB = process.env.OPENCODE_DB || join(process.env.USERPROFILE || process.env.HOME || ".", ".local", "share", "opencode", "opencode.db")
const safe = (v: unknown, n = 400) => typeof v === "string" ? v.slice(0, n) : v
const sanitizeText = (v: string) => v.replace(/(authorization\s*:\s*bearer\s+|(?:api[_-]?key|token|secret|password|passwd)\s*[=:]\s*)[^\s"']+/gi, "$1[REDACTED]").replace(/\b[A-Za-z0-9_+/=-]{32,}\b/g, "[REDACTED]")
const sanitizeCommand = (v: string) => sanitizeText(v).replace(/https?:\/\/[^\s]+/gi, "<url>").replace(/[A-Za-z]:\\[^ ]+|\/[^ ]+/g, "<path>")
function json(v: unknown): any { try { return typeof v === "string" ? JSON.parse(v) : v } catch { return undefined } }
function outputValue(v: any) { const x = v.output ?? v.result; if (typeof x === "string") return safe(x, 400); const ref = x?.path ?? x?.file ?? x?.outputPath ?? v.outputPath; return typeof ref === "string" && existsSync(ref) ? safe(readFileSync(ref, "utf8"), 400) : x }
function walk(v: any, sessionID: string, out: ReplayEvent[], seen = new Set<any>()) { if (!v || typeof v !== "object" || seen.has(v)) return; seen.add(v); if (Array.isArray(v)) return v.forEach(x => walk(x, sessionID, out, seen)); const tool = String(v.tool ?? v.name ?? ""); const input = v.input ?? v.args ?? v.state?.input; const command = typeof input === "string" ? input : input?.command ?? input?.cmd ?? input?.script; if (/^(shell|bash|cmd|powershell|pwsh|terminal|exec)$/i.test(tool) && typeof command === "string") out.push({ sessionID, id: String(v.callID ?? v.id ?? `${out.length}`), tool, input: { command: sanitizeCommand(safe(command, 1000)), cwd: safe(input?.cwd ?? v.cwd, 300), shell: safe(input?.shell ?? v.shell, 40) }, output: outputValue(v), at: v.at ?? v.time?.created }); Object.values(v).forEach(x => walk(x, sessionID, out, seen)) }
function readEvents(ids: string[], from?: number, to?: number, dbFile = DB) { const db = new Database(dbFile, { readonly: true }); const events: ReplayEvent[] = []; for (const id of ids) { let rows: any[] = []; try { rows = db.query("select id,type,data,time_created from session_message where session_id=? order by seq").all(id) as any[] } catch {} if (!rows.length) { try { rows = db.query("select id,type,data,time_created from message where session_id=? order by time_created").all(id) as any[] } catch {} } for (const row of rows) { if (from && row.time_created < from || to && row.time_created > to) continue; walk(json(row.data), id, events) } } db.close(); return events }
function fixtureEvents(file: string) { const x = json(readFileSync(file, "utf8")); return Array.isArray(x) ? x : x?.events || [] }
function main(argv = Bun.argv.slice(2)) { const ids: string[] = []; let fixture = "", from: number | undefined, to: number | undefined, repo: string | undefined, category: string | undefined, emit = "", keep = false, importReal = false; for (let i = 0; i < argv.length; i++) { const a = argv[i], n = argv[i + 1]; if (a === "--session") ids.push(n); else if (a === "--from") from = Number(n); else if (a === "--to") to = Number(n); else if (a === "--repo") repo = n; else if (a === "--category") category = n; else if (a === "--fixture") fixture = n; else if (a === "--emit-fixture") emit = n; else if (a === "--keep") keep = true; else if (a === "--import") importReal = true } if (!ids.length && !fixture) throw new Error("use --session ID (repeatable) or --fixture FILE"); if (importReal && !argv.includes("--confirm-import")) throw new Error("--import requires --confirm-import"); const events: ReplayEvent[] = fixture ? fixtureEvents(fixture) : readEvents(ids, from, to); const selected = events.filter(e => (!repo || e.input.cwd === repo) && (!category || e.tool === category)); const store = importReal ? process.env.OPENCODE_PAPERCUT_FILE || undefined : join(mkdtempSync(join(tmpdir(), "papercut-replay-")), "ledger.json"); let failures = 0, unknown = 0; const successes: string[] = []; for (const e of selected) { recordShell({ tool: e.tool, id: e.id, sessionID: e.sessionID, input: e.input }, e.output, store); const status = JSON.stringify(e.output ?? ""); if (/timeout|noResponse|cancel/i.test(status)) failures++; if (!/exitCode|code|status|timeout|cancel|noResponse/i.test(status)) unknown++; if (/"exitCode"\s*:\s*0|"code"\s*:\s*0/.test(status)) successes.push(e.input.command) } const rows = queryPapercuts({ repo }, store); const linked = new Set(rows.flatMap(r => r.solutions.map(s => s.command))); const rejected = successes.filter(c => !linked.has(c.replace(/[A-Za-z]:\\[^ ]+|\/[^ ]+/g, "<path>"))).length; if (emit) writeFileSync(emit, JSON.stringify({ schema: 1, events: selected.map(e => ({ ...e, input: { ...e.input, command: sanitizeCommand(safe(e.input.command, 240)) }, output: sanitizeText(safe(typeof e.output === "string" ? e.output : JSON.stringify(e.output), 240)) })) }, null, 2)); console.log(JSON.stringify({ dryRun: !importReal, sessions: [...new Set(selected.map(e => e.sessionID))].length, events: selected.length, failures, unknown, dedupeReduction: selected.length - rows.length, proposedLinks: rows.filter(r => r.solutions.length).length, rejectedUnrelatedLinks: rejected, storedOutputChars: JSON.stringify(rows).length, view_papercuts: formatPapercuts(rows) }, null, 2)); if (!keep && !importReal) rmSync(store!.replace(/\\[^\\]+$/, ""), { recursive: true, force: true }) }
if (import.meta.main) { try { main() } catch (e) { console.error(String(e)); process.exitCode = 2 } }
export { main, readEvents }
