import { resolveHostExecutable } from '../project-router/executable.mjs'
/** Anonymous installed-host test: stable prompts inserted while a Code Mode tool is busy. */
import {mkdirSync,writeFileSync} from 'node:fs'
import {join,resolve} from 'node:path'
import {pathToFileURL} from 'node:url'
const root=resolve(import.meta.dir,'..');const dir=resolve('.visual-e2e','session-guidance-'+Date.now()),plugin=join(dir,'plugin');mkdirSync(plugin,{recursive:true})
const calls:any[]=[];let supplied=false
const server=Bun.serve({port:0,async fetch(request){const body=await request.json() as any;calls.push(body.messages);const invoke=!supplied&&body.tools?.some((t:any)=>t.function?.name==='execute');if(invoke)supplied=true;const delta=invoke?{role:'assistant',tool_calls:[{index:0,id:'probe',type:'function',function:{name:'execute',arguments:JSON.stringify({code:'return await tools.guidance_probe({});'})}}]}:{role:'assistant',content:'FIXTURE_FINISHED'};return new Response([{id:'fixture',object:'chat.completion.chunk',model:'model',choices:[{index:0,delta,finish_reason:null}]},{id:'fixture',object:'chat.completion.chunk',model:'model',choices:[{index:0,delta:{},finish_reason:invoke?'tool_calls':'stop'}],usage:{prompt_tokens:10,completion_tokens:2}}].map(x=>'data: '+JSON.stringify(x)+'\n\n').join('')+'data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})}})
writeFileSync(join(plugin,'package.json'),JSON.stringify({name:'guidance-fixture',version:'1.0.0',main:'index.ts',type:'module'}))
writeFileSync(join(plugin,'index.ts'),`import {writeFileSync} from 'node:fs';import {define} from '@opencode-ai/plugin/v2/promise';import {SessionGuidance} from ${JSON.stringify(pathToFileURL(join(root,'quest/session-guidance.ts')).href)};import {QuestStore} from ${JSON.stringify(pathToFileURL(join(root,'quest/store.ts')).href)};const originalFetch=globalThis.fetch;globalThis.fetch=(input,options)=>{const url=String(input instanceof Request?input.url:input);return url.startsWith('http://127.0.0.1:')?originalFetch(input,options):Promise.resolve(new Response('Fixture only',{status:404}));};export default define({id:'guidance-fixture',async setup(ctx){await ctx.tool.transform(draft=>draft.add({name:'guidance_probe',description:'Local guidance fixture',input:{type:'object',properties:{}},output:{type:'object',additionalProperties:true},execute:async(_,c)=>{const receipts=[];for(const delivery of ['queue','steer']){const id=delivery==='queue'?'msg_00000000000000000000000001':'msg_00000000000000000000000002';for(let n=0;n<2;n++)receipts.push({delivery,n,result:await ctx.session.prompt({sessionID:c.sessionID,id,text:'GUIDANCE_'+delivery.toUpperCase(),delivery,resume:true})});}const store=new QuestStore(${JSON.stringify(dir)}),actual=await ctx.session.get({sessionID:c.sessionID}),project={id:'fixture',root:actual.location.directory},trusted={project,sessionID:'fixture-giver',requestID:'fixture'};store.create({id:'00000000000000000000000001',title:'Fixture',objective:'Guidance',project,integrationOwner:trusted.sessionID,sessions:[{callID:'run',runID:'run',sessionID:c.sessionID,parentID:trusted.sessionID,runtime:'native',role:'general',state:'executing',scope:{worktree:actual.location.directory},evidence:[],deliverables:[],attempt:1,updatedAt:new Date().toISOString()}]});const guide=new SessionGuidance(store,ctx.session,{supported:true}),input={questID:'00000000000000000000000001',runID:'run',text:'WRAPPER_GUIDANCE'};const a=await guide.send(trusted,input),b=await guide.send(trusted,input);const ack=guide.acknowledge({...trusted,sessionID:c.sessionID},{questID:input.questID,guidanceID:a.id});writeFileSync(${JSON.stringify(join(dir,'wrapper.json'))},JSON.stringify({a,b,ack,status:guide.status(trusted,input.questID)}));writeFileSync(${JSON.stringify(join(dir,'receipts.json'))},JSON.stringify(receipts));return {output:{ok:true},content:'PROBE_OK'}}}));}});`)
writeFileSync(join(dir,'opencode.jsonc'),JSON.stringify({plugin:['./plugin'],providers:{'guidance-fixture':{package:'@opencode-ai/ai/providers/openai-compatible',env:[],settings:{baseURL:'http://127.0.0.1:'+server.port+'/v1',apiKey:'fixture'},models:{model:{limit:{context:128000,output:2000}}}}}}))
const proc=Bun.spawn([resolveHostExecutable(),'run','--standalone','--auto','--agent','general','-m','guidance-fixture/model','Exercise the local guidance fixture.'],{cwd:dir,env:{...process.env,OPENCODE_CONFIG_DIR:dir,OPENCODE_CONFIG_PROJECT_DISABLE:'1',CODEX_HOME:join(dir,'empty-codex'),XDG_DATA_HOME:join(dir,'data'),XDG_STATE_HOME:join(dir,'state'),XDG_CACHE_HOME:join(dir,'cache'),OPENCODE_DB:join(dir,'host.db'),OPENCODE_DISABLE_AUTOUPDATE:'1'},stdin:'ignore',stdout:'pipe',stderr:'pipe',windowsHide:true})
const timer=setTimeout(()=>proc.kill(),45000)
try{const [exitCode,out,err]=await Promise.all([proc.exited,new Response(proc.stdout).text(),new Response(proc.stderr).text()]);let receipts:any[]=[];try{receipts=await Bun.file(join(dir,'receipts.json')).json()}catch{};let wrapper:any={};try{wrapper=await Bun.file(join(dir,'wrapper.json')).json()}catch{};const checks={wrapper:wrapper.a?.state==='submitted'&&wrapper.a.id===wrapper.b?.id&&wrapper.ack?.state==='acknowledged'&&wrapper.status?.length===1,host:exitCode===0,receipts:receipts.length===4,stable:receipts.length===4&&receipts.every(r=>(r.result?.data??r.result)?.id===(r.delivery==='queue'?'msg_00000000000000000000000001':'msg_00000000000000000000000002')),steerObserved:calls.some(messages=>messages.some((m:any)=>m.role==='user'&&JSON.stringify(m.content).includes('GUIDANCE_STEER'))),deduplicated:calls.every(messages=>['GUIDANCE_STEER','GUIDANCE_QUEUE'].every(marker=>messages.filter((m:any)=>m.role==='user'&&JSON.stringify(m.content).includes(marker)).length<=1)),boundaryOrder:calls.findIndex(messages=>messages.some((m:any)=>m.role==='user'&&JSON.stringify(m.content).includes('GUIDANCE_STEER')))<calls.findIndex(messages=>messages.some((m:any)=>m.role==='user'&&JSON.stringify(m.content).includes('GUIDANCE_QUEUE'))),queueObserved:calls.some(messages=>messages.some((m:any)=>m.role==='user'&&JSON.stringify(m.content).includes('GUIDANCE_QUEUE')))};const ok=Object.values(checks).every(Boolean);writeFileSync(join(dir,'report.json'),JSON.stringify({ok,checks,receipts,calls,out,err},null,2));console.log(JSON.stringify({ok,checks,report:join(dir,'report.json')}));process.exitCode=ok?0:1}finally{clearTimeout(timer);server.stop()}
