import { resolveHostExecutable } from '../project-router/executable.mjs'
/** Actual host workflow with synthetic provider counters. These counters verify capture, not measured cost or model speed. */
import {mkdirSync,writeFileSync,readFileSync,existsSync} from "node:fs"
import {join,resolve} from "node:path"
import {pathToFileURL} from "node:url"
import {QuestStore} from "../quest/store"
import {readAllQuests} from "../quest/index"
const root=resolve(import.meta.dir,".."),dir=join(root,".visual-e2e","parallel-worker-host-"+Date.now()),ledger=join(dir,"ledger")
mkdirSync(dir,{recursive:true});writeFileSync(join(dir,".gitignore"),"cache/\ndata/\nstate/\nledger/\n.claude/\n*.db*\n*.jsonl\nprovider-*.json\naccounts.json\n");mkdirSync(join(dir,"empty-auth"));for(const args of [["init",dir],["-C",dir,"add",".gitignore"],["-C",dir,"-c","user.name=Fixture","-c","user.email=fixture@example.invalid","commit","--allow-empty","-m","Fixture base"]]){if(Bun.spawnSync(["git",...args],{windowsHide:true}).exitCode!==0)throw new Error("Fixture Git setup failed")}
const store=new QuestStore(ledger),quest=()=>readAllQuests(ledger,{includeArchived:true}).find(q=>q.quest)?.quest
let calls=0,workerCalls=0,parentResult=false,outcomeResult=false,overlap=false,integrationReady=false,combinedRead=false
const entered=new Set<string>()
let outcomeReport:any
const syntheticUsage={prompt_tokens:100,completion_tokens:10,prompt_tokens_details:{cached_tokens:20},completion_tokens_details:{reasoning_tokens:0}}
const chunk=(content:string)=>[{id:"fixture",object:"chat.completion.chunk",model:"model",choices:[{index:0,delta:{content},finish_reason:"stop"}],usage:syntheticUsage}]
const call=(name:string,input:any)=>[{id:"fixture",object:"chat.completion.chunk",model:"model",choices:[{index:0,delta:{role:"assistant",tool_calls:[{index:0,id:"fixture-"+calls,type:"function",function:{name,arguments:JSON.stringify(input)}}]},finish_reason:null}]},{id:"fixture",object:"chat.completion.chunk",model:"model",choices:[{index:0,delta:{},finish_reason:"tool_calls"}],usage:syntheticUsage}]
const server=Bun.serve({port:0,async fetch(request){const p=await request.json() as any;calls++;writeFileSync(join(dir,"provider-"+calls+".json"),JSON.stringify(p));let chunks:any[];const tools=p.tools??[],messages=p.messages??[],results=messages.filter((m:any)=>m.role==="tool"),worker=JSON.stringify(messages).includes("Assigned steps:")
 if(!tools.length)chunks=chunk("Fixture title")
 else if(worker){
  workerCalls++;const q=quest()!,id=p.model==='a/model'?'a':p.model==='b/model'?'b':'integrate',session=[...q.sessions].reverse().find(s=>s.deliverables.includes(id))!,path=String(session.scope?.worktree)
  if(!results.length&&id!=='integrate'){
   entered.add(id);const until=Date.now()+15000;while(entered.size<2&&!overlap&&Date.now()<until)await Bun.sleep(50)
   overlap ||= entered.size===2;entered.delete(id);chunks=call("write",{path:join(path,id+".txt"),content:id.toUpperCase()})
  }else if(!results.length){integrationReady=["a","b"].every(step=>q.stages.find(s=>s.id===step)?.status==="done"&&q.sessions.some(s=>s.deliverables.includes(step)&&s.state==="completed"));chunks=call("read",{path:join(path,"a.txt")})}
  else if(id==='integrate'&&results.length===1)chunks=call("read",{path:join(path,"b.txt")})
  else if(id==='integrate'&&results.length===2){combinedRead=String(results[0].content).split('\n').includes('1: A')&&String(results[1].content).split('\n').includes('1: B');chunks=call("write",{path:join(path,"combined.txt"),content:combinedRead?'A+B':'READ_FAILED'})}
  else if(results.length===(id==='integrate'?3:1))chunks=call("execute",{code:"return await tools.quest({action:'update',id:"+JSON.stringify(q.id)+",update:{steps:[{id:"+JSON.stringify(id)+",state:'done',note:'Native tools produced and checked output'}]}})"})
  else chunks=chunk("WORKER_DONE")
 }else if(!results.length){chunks=call("execute",{code:"const q=await tools.quest({action:'create',create:{title:'Native parallel worker fixture',description:'Verify independent workers and combined result',steps:[{id:'a',title:'Write A'},{id:'b',title:'Write B'},{id:'integrate',title:'Read and combine both worker outputs',needs:['a','b']}]}});const run=await tools.quest({action:'run',id:q.id,run:{continue:true,maxConcurrent:2,model:'worker-fixture/integrate/model',stepModels:{a:'worker-fixture/a/model',b:'worker-fixture/b/model'}}});return {marker:'ROOT_STARTED',id:q.id,run};"})}
 else {parentResult=results.some((m:any)=>String(m.content).includes("ROOT_STARTED"));const deadline=Date.now()+90000;while(parentResult&&Date.now()<deadline&&!quest()?.sessions.some(s=>s.deliverables.includes('integrate')&&s.state==="completed"))await Bun.sleep(50);if(results.length===1&&quest()?.sessions.some(s=>s.deliverables.includes('integrate')&&s.state==='completed'))chunks=call('execute',{code:"const report=await tools.quest_outcome({action:'report',exportHTML:true,questID:"+JSON.stringify(quest()!.id)+"});return {marker:'OUTCOMES_RECORDED',report};"});else {const reported=results.find((m:any)=>String(m.content).includes('OUTCOMES_RECORDED'));outcomeResult=!!reported;if(reported)outcomeReport=JSON.parse(reported.content)?.report?.report;chunks=chunk(parentResult?"ROOT_DONE":"ROOT_FAILED")}}

 return new Response(chunks.map(c=>"data: "+JSON.stringify(c)+"\n\n").join("")+"data: [DONE]\n\n",{headers:{"content-type":"text/event-stream"}})
}})
const plugin=join(dir,"plugin");mkdirSync(plugin);const url=(p:string)=>JSON.stringify(pathToFileURL(join(root,p)).href)
writeFileSync(join(plugin,"package.json"),JSON.stringify({name:"worker-fixture",version:"1.0.0",main:"index.ts",type:"module"}))
const fixturePolicy=join(dir,"dispatch-policy.json"),fixtureAccount={id:"fixture-account",provider:"openai",plan:{name:"fixture",rateLimitTier:null,multiplier:null,provenance:"provider-observed",observedAt:new Date().toISOString()},state:"available",observedAt:new Date().toISOString(),connections:[{owner:"opencode",routeProviders:["worker-fixture"],modelPrefix:null}],windows:[{id:"shared",scope:"shared",label:"Fixture pool",state:"available",usedPercent:0,observedAt:new Date().toISOString(),remainingPercent:100,resetAt:new Date(Date.now()+3600000).toISOString()}]}
const accounts=['a','b','integrate'].map(id=>({...fixtureAccount,id:'fixture-'+id,connections:[{owner:'opencode',routeProviders:['worker-fixture'],modelPrefix:id}]}))
writeFileSync(fixturePolicy,JSON.stringify({version:1,request:{task:"coding",minSuccessRate:0.9,minTrials:5,qualityTolerance:0.02,maxUsageAgeSeconds:120,maxEvidenceAgeDays:30,maxCashPerSuccess:0,reserveFraction:0,allowedRouteIDs:['a','b','integrate']},routes:['a','b','integrate'].map(id=>({id,accountID:'fixture-'+id,providerID:'worker-fixture',modelID:id+'/model',harness:'native',agent:'general',reasoning:'unknown',serviceTier:'default',verified:true,admission:'configured-choice',evidence:[],quotaPerTask:{}})),billing:Object.fromEntries(accounts.map(a=>[a.id,'subscription'])),bootstrapByProject:{}}))
mkdirSync(join(dir,"models"));writeFileSync(join(dir,"models","access-policy.json"),JSON.stringify({version:1,routes:[{providerID:"worker-fixture",modelPattern:"(a|b|integrate)/model",transports:[{origin:"http://127.0.0.1:"+server.port,pathPrefix:"/v1/"}]}]}))
writeFileSync(join(plugin,"index.ts"),`
import {appendFileSync} from "node:fs";const receipt=stage=>appendFileSync(${JSON.stringify(join(dir,"setup.jsonl"))},JSON.stringify({stage,at:Date.now()})+"\\n");
import {reserveDispatch} from ${url('models/dispatch-planner.ts')};
import quests from ${url('quest/server.ts')}; import usage from ${url('usage/server.ts')};
import {trackedStart,collectWorkflowOutcomes} from ${url('quest/outcome-tracking.ts')};import {QuestStore} from ${url('quest/store.ts')}; import {typedQuestTool} from ${url('quest/typed-tool.ts')};
import {startQuestRun} from ${url('quest/runtime.ts')}; import {QuestContinuation} from ${url('quest/continuation.ts')}; import {projectIdentity} from ${url('quest/project.ts')};
const fixtureUsage=async()=>({schema:1,updatedAt:new Date().toISOString(),accounts:${JSON.stringify(accounts)}.map(a=>({...a,observedAt:new Date().toISOString(),windows:a.windows.map(w=>({...w,observedAt:new Date().toISOString()}))})),diagnostics:[]});
export default {id:'native-parallel-fixture',async setup(ctx){const trace=(obj,path)=>new Proxy(obj,{get(target,key){const value=Reflect.get(target,key,target);if(typeof value==='function')return (...args)=>{const label=path+'.'+String(key)+(typeof args[0]==='string'?':'+args[0]:'');receipt(label+':begin');try{const result=Reflect.apply(value,target,args);if(result&&typeof result.then==='function')return result.then(value=>{receipt(label+':end');return value},error=>{receipt(label+':error');throw error});receipt(label+':end');return result}catch(error){receipt(label+':error');throw error}};return value&&typeof value==='object'&&['tool','session','event'].includes(String(key))?trace(value,path+'.'+String(key)):value}});ctx=trace(ctx,'ctx');receipt('start');await quests.setup(ctx);receipt('quests');await usage.setup(ctx);receipt('usage');const store=new QuestStore(${JSON.stringify(ledger)});const start=trackedStart(store,startQuestRun(store,ctx.session,{policyFile:'fixture-only',reserve:async input=>reserveDispatch({...input,policyFile:${JSON.stringify(fixturePolicy)}},fixtureUsage)}));const options={refresh:fixtureUsage};const continuation=new QuestContinuation(store,start,options);const tick=setInterval(()=>Promise.all([continuation.tick(),new QuestContinuation(store,start,options).tick()]).then(()=>collectWorkflowOutcomes(store)).catch(console.error),500);tick.unref();const tool=typedQuestTool(store,ctx.session,{startRun:start});const execute=tool.execute;tool.execute=async(input,context)=>{if(input.action==='run'&&input.run?.continue){const session=await ctx.session.get({sessionID:context.sessionID});const result=await continuation.run(input.id,input.run,{project:projectIdentity((session.data??session).location.directory),sessionID:context.sessionID,requestID:context.id??context.callID});return {output:JSON.parse(JSON.stringify(result)),content:JSON.stringify(result)}}return execute(input,context)};await ctx.tool.transform(draft=>draft.update('quest',entry=>Object.assign(entry,tool)));receipt('ready');}}
`)

writeFileSync(join(dir,"opencode.jsonc"),JSON.stringify({plugin:["./plugin"],providers:{"worker-fixture":{package:"@opencode-ai/ai/providers/openai-compatible",env:[],settings:{baseURL:"http://127.0.0.1:"+server.port+"/v1",apiKey:"fixture-only"},models:Object.fromEntries(['model','a/model','b/model','integrate/model'].map(id=>[id,{limit:{context:128000,output:1000}}]))}}}))
const telemetry=join(dir,"requests.jsonl"),proc=Bun.spawn([resolveHostExecutable(),"run","--standalone","--agent","general","-m","worker-fixture/integrate/model","Run the native parallel worker fixture"],{cwd:dir,env:{...process.env,OPENCODE_CONFIG_DIR:dir,OPENCODE_CONFIG_PROJECT_DISABLE:"1",OPENCODE_QUEST_ROOT:ledger,OPENCODE_QUEST_SETTINGS:join(dir,"quest-settings.json"),CODEX_HOME:join(dir,"empty-auth"),OPENCODE_ORCHESTRATION_LEDGER:join(ledger,"orchestration.jsonl"),OPENCODE_CAPACITY_FILE:join(ledger,"capacity.json"),OPENCODE_ACCOUNT_DISCOVERY_ROOT:join(dir,"empty-auth"),OPENCODE_ACCOUNT_USAGE_FILE:join(dir,"accounts.json"),OPENCODE_TELEMETRY_FILE:telemetry,OPENCODE_DB:join(dir,"host.db"),XDG_DATA_HOME:join(dir,"data"),XDG_STATE_HOME:join(dir,"state"),XDG_CACHE_HOME:join(dir,"cache"),OPENCODE_DISABLE_AUTOUPDATE:"1"},stdin:"ignore",stdout:"pipe",stderr:"pipe",windowsHide:true})
const timer=setTimeout(()=>proc.kill(),120000)
try{
 const[code,out,err]=await Promise.all([proc.exited,new Response(proc.stdout).text(),new Response(proc.stderr).text()]),q=quest()
 const workspaces=q?.sessions.map(s=>{const file=join(store.runtime,'workspaces',s.runID+'.json');return existsSync(file)?JSON.parse(readFileSync(file,'utf8')):null})??[]
 const integrated=workspaces.find(w=>q?.sessions.find(s=>s.runID===w?.runID)?.deliverables.includes('integrate'))
 const combined=integrated&&existsSync(join(integrated.path,'combined.txt'))?readFileSync(join(integrated.path,'combined.txt'),'utf8'):null
 const continuation=existsSync(join(store.runtime,'continuations.json'))?JSON.parse(readFileSync(join(store.runtime,'continuations.json'),'utf8')):[]
 const numericWorkflowTokens=outcomeReport?.runs?.length===3&&outcomeReport.runs.every((run:any)=>run.observation?.state==='completed'&&['input','cacheRead','cacheWrite','output','reasoning'].every(key=>typeof run.observation.tokens?.[key]==='number'&&Number.isFinite(run.observation.tokens[key])&&run.observation.tokens[key]>=0))
 const checks={numericWorkflowTokens,host:code===0,parentResult,outcomeResult,overlap,integrationReady,combinedRead,combined:combined==='A+B',distinctWorktrees:new Set(workspaces.map(w=>w?.path)).size===3,threeRuns:q?.sessions.length===3,completed:q?.sessions.every(s=>s.state==='completed')===true,steps:q?.stages.every(s=>s.status==='done')===true,inherited:integrated?.inheritedRunIDs?.length===2,stableAdmissions:continuation[0]?.admissions?.length===3&&continuation[0].admissions.every(a=>a.attempt===1)}
 const ok=Object.values(checks).every(Boolean);writeFileSync(join(dir,'report.json'),JSON.stringify({ok,checks,counterProvenance:'Synthetic provider counters verify capture only; they are not measured plan cost or model speed',syntheticUsage,outcomeReport,calls,workerCalls,code,out,err,quest:q,workspaces,continuation},null,2));console.log(JSON.stringify({ok,checks,report:join(dir,'report.json')}));process.exitCode=ok?0:1
}finally{clearTimeout(timer);server.stop(true)}
