import { resolveHostExecutable } from '../project-router/executable.mjs'
/** Exercises installed Code Mode -> session burn calculation surface with an anonymous local provider. */
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs'
import {join,resolve} from 'node:path'
import {pathToFileURL} from 'node:url'
const root=resolve(import.meta.dir,'..'),dir=join(root,'.visual-e2e','session-burn-host-'+Date.now()),plugin=join(dir,'plugin'),home=join(dir,'home')
mkdirSync(plugin,{recursive:true});mkdirSync(join(home,'.local/share/opencode'),{recursive:true})
writeFileSync(join(home,'.local/share/opencode/auth.json'),JSON.stringify({openai:{type:'oauth',access:'FIXTURE_ONLY',accountId:'fixture-account'}}))
let sawExecute=false,sawResult=false
const code='const s=await tools.usage_status({format:"json"});const a=s.accounts[0],w=a.windows.find(w=>w.scope==="shared");await tools.usage_target({accountID:a.id,deadlineAt:Date.now()+60000,reservePoints:0,questPacing:{windowID:w.id,maxConcurrent:4}});const r=await tools.usage_status({format:"json"});return {marker:"SESSION_BURN_HOST_TOOL_OK",control:r.burnControl,sessionBurn:r.accounting.sessionBurn};'
const server=Bun.serve({port:0,async fetch(request){const body=await request.json() as any,tool=body.tools?.some((t:any)=>t.function?.name==='execute'),result=body.messages?.some((m:any)=>m.role==='tool'&&JSON.stringify(m.content).includes('SESSION_BURN_HOST_TOOL_OK'));if(result){const text=JSON.stringify(body.messages.filter((m:any)=>m.role==='tool'));sawResult=text.includes('uncachedInput')&&text.includes('chronologicalTestedIntervals')&&text.includes('rateBasis')}
 const invoke=tool&&!body.messages?.some((m:any)=>m.role==='tool');if(invoke)sawExecute=true
 const delta=invoke?{role:'assistant',tool_calls:[{index:0,id:'burn_call',type:'function',function:{name:'execute',arguments:JSON.stringify({code})}}]}:{role:'assistant',content:'SESSION_BURN_HOST_OK'}
 const chunks=[{id:'fixture',object:'chat.completion.chunk',model:'model',choices:[{index:0,delta,finish_reason:null}]},{id:'fixture',object:'chat.completion.chunk',model:'model',choices:[{index:0,delta:{},finish_reason:invoke?'tool_calls':'stop'}],usage:{prompt_tokens:120,completion_tokens:12}}]
 return new Response(chunks.map(c=>'data: '+JSON.stringify(c)+'\n\n').join('')+'data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})
}})
writeFileSync(join(plugin,'package.json'),JSON.stringify({name:'burn-fixture',version:'1.0.0',main:'index.ts',type:'module'}))
writeFileSync(join(plugin,'index.ts'),`const realFetch=globalThis.fetch;globalThis.fetch=(input,options)=>{const url=String(input instanceof Request?input.url:input);if(url==='https://chatgpt.com/backend-api/wham/usage')return Promise.resolve(Response.json({account_id:'fixture-account',plan_type:'pro',rate_limit:{primary_window:{used_percent:25,limit_window_seconds:604800,reset_at:Math.floor(Date.now()/1000)+3600}}}));if(url.startsWith('http://127.0.0.1:'))return realFetch(input,options);return Promise.resolve(new Response('Fixture only',{status:404}));};export {default} from ${JSON.stringify(pathToFileURL(join(root,'usage/server.ts')).href)};`)
writeFileSync(join(dir,'opencode.jsonc'),JSON.stringify({plugin:['./plugin'],providers:{'burn-fixture':{package:'@opencode-ai/ai/providers/openai-compatible',env:[],settings:{baseURL:'http://127.0.0.1:'+server.port+'/v1',apiKey:'fixture'},models:{model:{limit:{context:128000,output:2000}}}}}}))
const telemetry=join(dir,'requests.jsonl'),proc=Bun.spawn([resolveHostExecutable(),'run','--standalone','--auto','--agent','general','-m','burn-fixture/model','Exercise the local burn pacing tool fixture.'],{cwd:dir,env:{...process.env,OPENCODE_CONFIG_DIR:dir,OPENCODE_CONFIG_PROJECT_DISABLE:'1',CODEX_HOME:join(dir,'empty-codex'),XDG_DATA_HOME:join(dir,'data'),XDG_STATE_HOME:join(dir,'state'),XDG_CACHE_HOME:join(dir,'cache'),OPENCODE_ACCOUNT_DISCOVERY_ROOT:home,OPENCODE_ACCOUNT_USAGE_FILE:join(dir,'accounts.json'),OPENCODE_TELEMETRY_FILE:telemetry,OPENCODE_PASSIVE_LEDGER_FILE:telemetry+'.ledger.sqlite',OPENCODE_DB:join(dir,'host.db'),OPENCODE_DISABLE_AUTOUPDATE:'1'},stdin:'ignore',stdout:'pipe',stderr:'pipe',windowsHide:true})
const timer=setTimeout(()=>proc.kill(),60000)
try{const [exitCode,out,err]=await Promise.all([proc.exited,new Response(proc.stdout).text(),new Response(proc.stderr).text()]);let targets:any[]=[],controls:any[]=[];try{targets=JSON.parse(readFileSync(telemetry+'.targets.json','utf8'));controls=JSON.parse(readFileSync(telemetry+'.burn-control.json','utf8'))}catch{}
 const checks={host:exitCode===0,execute:sawExecute,result:sawResult,target:targets[0]?.pacing?.maxConcurrent===4,persisted:controls[0]?.state==='ready'&&controls[0]?.desiredConcurrency===1&&controls[0]?.maxConcurrent===4},ok=Object.values(checks).every(Boolean),report=join(dir,'report.json');writeFileSync(report,JSON.stringify({ok,checks,exitCode,out,err},null,2));console.log(JSON.stringify({ok,checks,report}));process.exitCode=ok?0:1
}finally{clearTimeout(timer);server.stop()}
