/** Real installed dispatch, worker completion, automatic giver response and native navigation. */
import {EmbeddedTerminalRenderable,KeyEvent} from '@opentui/core'
import {createTestRenderer} from '@opentui/core/testing'
import {Resvg} from '@resvg/resvg-js'
import {frameToSvg,HOST_PALETTE} from '../ui-lab/frame-html'
import {Database} from 'bun:sqlite'
import {spawn} from 'node:child_process'
import {mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs'
import {join,resolve} from 'node:path'
import {QuestStore} from '../quest/store'
import {projectIdentity} from '../quest/project'
import {freePort} from './plugin-deploy'
const root=resolve(process.argv[2]),reservations=resolve(process.argv[3]),output=join(root,'.visual-e2e','installed-dispatch-'+Date.now())
const policy=JSON.parse(readFileSync(join(root,'models/dispatch-policy.json'),'utf8')),route=policy.routes.find((r:any)=>r.id===policy.request.primaryRouteID)
const holds=()=>JSON.parse(readFileSync(reservations,'utf8')).reservations.filter((r:any)=>r.accountID===route.accountID&&r.exclusive&&['active','unknown'].includes(r.state))
if(holds().length)throw Error('Existing uncertain account ownership blocks this successful dispatch check; inspect it first')
const project=projectIdentity(root),model='cliproxyapi/gpt-5.6-luna#medium',workerModel=route.providerID+'/'+route.modelID+'#'+route.reasoning
const sourceCommit=JSON.parse(readFileSync(join(root,'plugin-activation.json'),'utf8')).evidence.sourceCommit
mkdirSync(output,{recursive:true});const report:any={ok:false,scope:'Real configured worker dispatch, persisted step and terminal outcome, automatic giver return, native worker navigation',sourceCommit,model,workerModel,runs:[]}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms))
for(let number=1;number<=2;number++){
 if(holds().length)throw Error('An account worker is still active or unknown; no duplicate launch')
 const dir=join(output,'run-'+number);mkdirSync(dir,{recursive:true});const database=join(dir,'host.db'),store=new QuestStore(join(dir,'ledger'))
 const q=store.create({id:'01j0000000000000000000098'+number,title:'Verify installed Quest worker flow '+number,objective:'Read AGENTS.md and save the assigned result',description:'Read only the AGENTS.md in your assigned working directory. Record the phrase INSTALLED_QUEST_WORKER_VERIFIED and one instruction from that file in the assigned step note using quest update.steps with state done. Read the Quest back to confirm the step saved. Do not write files, run shell commands or delegate.',contractVersion:2,project,stages:[{id:'inspect',title:'Read AGENTS.md, save the actual finding and verify the saved step',status:'pending',needs:[]}]})
 const setup=await createTestRenderer({width:150,height:52}),terminal=new EmbeddedTerminalRenderable(setup.renderer,{id:'hold-check',width:150,height:52,cols:150,rows:52,maxScrollback:100000});setup.renderer.root.add(terminal);terminal.focus()
 const env={...process.env,OPENCODE_CONFIG_DIR:root,OPENCODE_CONFIG_PROJECT_DISABLE:'1',OPENCODE_RELEASE_CHANNEL:'dev',OPENCODE_DB:database,OPENCODE_QUEST_ROOT:store.projectRoot,OPENCODE_ROUTE_RESERVATIONS:reservations,OPENCODE_ORCHESTRATION_LEDGER:join(dir,'orchestration.jsonl'),OPENCODE_TELEMETRY_FILE:join(dir,'requests.jsonl'),XDG_STATE_HOME:join(dir,'state'),OPENCODE_DISABLE_AUTOUPDATE:'1',CLAUDE_CODE_BRIDGE_PORT:String(await freePort())}
 const child=spawn('node',[join(root,'scripts/opencode-runtime.mjs'),'--json','--auto','--cwd',root,'--model',model,'--agent','quest-giver','--cols','150','--rows','52'],{cwd:root,env,windowsHide:true,stdio:['pipe','pipe','pipe']})
 let buffer='',errors='',exited=false,db:Database|undefined;const events:any[]=[],row:any={number,ok:false,screenshots:[]}
 child.stdout.on('data',chunk=>{buffer+=chunk;for(;;){const n=buffer.indexOf('\n');if(n<0)break;const line=buffer.slice(0,n);buffer=buffer.slice(n+1);try{const e=JSON.parse(line);if(e.type==='data')terminal.write(Buffer.from(e.data,'base64').toString());else events.push(e)}catch{errors+=line}}});child.stderr.on('data',x=>errors+=x);child.on('exit',()=>exited=true)
 const send=(data:string)=>child.stdin.write(JSON.stringify({type:'write',data:Buffer.from(data).toString('base64')})+'\n');terminal.onData=data=>send(Buffer.from(data).toString())
 const frame=async()=>{await setup.renderOnce();return terminal.screen().text}
 async function wait(label:string,check:()=>any,timeout=60000){const end=Date.now()+timeout;while(Date.now()<end){if(await check())return;if(exited)throw Error(label+': host exited '+errors);await sleep(300)}throw Error(label+': timed out')}
 async function capture(name:string){await setup.renderOnce();const path=join(dir,name+'.png');writeFileSync(path,new Resvg(frameToSvg(setup.captureSpans(),name,HOST_PALETTE),{font:{loadSystemFonts:true}}).render().asPng());writeFileSync(join(dir,name+'.txt'),await frame());row.screenshots.push(path)}
 async function key(name:string,sequence:string){send(Buffer.from(terminal.encodeKey(new KeyEvent({name,sequence,raw:sequence,ctrl:false,meta:false,shift:false,option:false,number:false,eventType:'press',source:'raw'}))).toString());await sleep(350)}
 async function command(text:string){send(Buffer.from(terminal.encodePaste(new TextEncoder().encode(text))).toString());await sleep(1000);await key('return','\r')}
 try{
  await wait('plugin load',()=>{const e=events.find(e=>e.type==='launched');if(!e||!existsSync(e.receipt))return false;row.loads=readFileSync(e.receipt,'utf8').trim().split('\n').map(s=>JSON.parse(s));return row.loads.some((l:any)=>l.component==='tui:quests'&&l.sourceCommit===sourceCommit)})
  await wait('composer',async()=>(await frame()).includes('Quests'));await sleep(1000)
  await command(`Use the existing Quest titled ${q.title}, id ${q.id}. Call the native quest tool action run exactly once with id ${q.id} and run {stepIDs:["inspect"],model:"${workerModel}",readOnly:true}. Respect account admission and quota. Do not create Quests, retry, change models, change settings, release holds, or implement anything. Briefly report admission or the exact tool failure, then finish without polling or another prompt. If an automatic Quest worker update arrives, inspect the saved Quest using get, report the saved step finding and actual worker outcome (or exact failure), then finish without dispatch.`)
  await wait('giver persisted',()=>{if(!existsSync(database))return false;db??=new Database(database,{readonly:true});const found:any=db.query('select id from session_v2 where parent_id is null order by time_created asc').get();row.sessionID=found?.id;return !!row.sessionID})
  await wait('worker bound',()=>!!store.read(q.id)?.sessions[0]?.sessionID)
  await command('/quests');await wait('live board',async()=>(await frame()).includes('Search quests'));await wait('confirmed running',async()=>(await frame()).includes('RUNNING · Saved: executing'));await capture('worker-running');const firstCheck=(await frame()).match(/Checked: ([^\n]+)/)?.[1];await sleep(4500);await capture('worker-activity-update');row.liveUpdates=firstCheck!==(await frame()).match(/Checked: ([^\n]+)/)?.[1]
  await key('n','n');await wait('native composer dialog',async()=>(await frame()).includes('Nudge Quest Giver'));await capture('composer');await key('escape','\x1b');row.composer=true
  await wait('automatic worker response',()=>{const all:any[]=db!.query('select type,data from session_message where session_id=? order by seq').all(row.sessionID);const messages=all.map(r=>({type:r.type,...JSON.parse(r.data)}));row.messages=messages.map(m=>({...m,content:m.content?.filter((p:any)=>p.type!=='reasoning')}));const at=messages.findIndex(m=>m.type==='user'&&JSON.stringify(m).includes('Automatic Quest worker update'));row.automaticReturn=at>=0&&messages.slice(at+1).some(m=>m.type==='assistant'&&m.time?.completed&&m.finish==='stop');return row.automaticReturn},240000)
  await wait('completed live board',async()=>(await frame()).includes('COMPLETED · Saved: completed'));await capture('completed-board');await key('escape','\x1b');await wait('giver response visible',async()=>!(await frame()).includes('Search quests'));await capture('automatic-worker-response');await command('/quests');await wait('board',async()=>(await frame()).includes('Search quests'));await key('w','w');await wait('native worker transcript',async()=>(await frame()).includes('INSTALLED_QUEST_WORKER_VERIFIED')&&!(await frame()).includes('Search quests'));await capture('actual-worker');await command('/quest-back');await wait('returned to Quest',async()=>(await frame()).includes('QUEST STEPS'));await capture('returned-board')
  row.quest=new QuestStore(store.projectRoot).read(q.id);const run=row.quest.sessions[0];row.singleWorker=row.quest.sessions.length===1&&run?.state==='completed'&&!!run.sessionID;row.savedStep=row.quest.stages[0].status==='done'&&row.quest.stages[0].note?.includes('INSTALLED_QUEST_WORKER_VERIFIED');row.terminal=db!.query('select idle_outcome,model from session_v2 where id=?').get(run?.sessionID??'');row.workerMessages=db!.query('select type,data from session_message where session_id=? order by seq').all(run?.sessionID??'').map((r:any)=>({type:r.type,...JSON.parse(r.data)})).map((m:any)=>({...m,content:m.content?.filter((p:any)=>p.type!=='reasoning')}));row.exactModel=row.workerMessages.some((m:any)=>m.type==='assistant'&&m.model?.providerID===route.providerID&&m.model?.id===route.modelID&&m.model?.variant===route.reasoning);row.reservation=JSON.parse(readFileSync(reservations,'utf8')).reservations.find((r:any)=>r.runID===run?.runID);row.ok=row.liveUpdates&&row.composer&&row.automaticReturn&&row.singleWorker&&row.savedStep&&row.exactModel&&row.terminal?.idle_outcome==='succeeded'&&row.reservation?.state==='settled'
 }catch(e){row.error=String(e);await capture('failure')}
 finally{db?.close();terminal.onData=undefined;if(!exited)child.stdin.write(JSON.stringify({type:'stop'})+'\n');await sleep(1500);terminal.destroy();setup.renderer.destroy();row.events=events;row.errors=errors;report.runs.push(row);writeFileSync(join(output,'report.json'),JSON.stringify(report,null,2))}
 console.log(JSON.stringify({number,ok:row.ok,error:row.error,output:dir}));if(!row.ok)break
}
report.ok=report.runs.length===2&&report.runs.every((r:any)=>r.ok);writeFileSync(join(output,'report.json'),JSON.stringify(report,null,2));console.log(join(output,'report.json'));process.exitCode=report.ok?0:1
