import { resolveHostExecutable } from '../project-router/executable.mjs'
import {QuestWorkspaces} from '../quest/workspaces'
/** Isolated real native Astra worker, driven by a deterministic local coordinator. */
import {mkdirSync,writeFileSync,readFileSync,cpSync,existsSync} from 'node:fs'
import {join,resolve} from 'node:path'
import {pathToFileURL} from 'node:url'
import {homedir} from 'node:os'
import {parse} from 'json5'
import {Database} from 'bun:sqlite'
import {QuestStore} from '../quest/store'
import {projectIdentity} from '../quest/project'
const shared=process.argv.includes('--shared')
if(shared&&process.argv.includes('--prepared'))throw new Error('Select shared or prepared verification')
const root=resolve(import.meta.dir,'..'),dir=join(root,'.visual-e2e','astra-capability-'+Date.now()),ledger=join(dir,'ledger'),model='openai/gpt-6-astra#medium'
mkdirSync(dir,{recursive:true})
writeFileSync(join(dir,'.gitignore'),'ledger/\n.claude/\nplugin/\n*.db*\n*.json\n*.jsonc\n')
writeFileSync(join(dir,'AGENTS.md'),'This is an isolated capability fixture. Edit only capability.txt and result.json in your assigned workspace. Run a harmless shell check. Report actual results through quest update. Do not create Quests, spawn workers, commit, deploy or access unrelated files.\n')
writeFileSync(join(dir,'README.md'),'Capability acceptance fixture, not configuration maintenance.\n')
for(const args of [['init'],['add','.gitignore','AGENTS.md','README.md'],['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','Isolated capability fixture']])if(Bun.spawnSync(['git','-C',dir,...args],{windowsHide:true}).exitCode)throw new Error('Fixture git setup failed')
const existingHolds=join(homedir(),'.opencode/.quest-runtime/route-reservations.json')
if(existsSync(existingHolds)&&JSON.parse(readFileSync(existingHolds,'utf8')).reservations.some((r:any)=>['active','unknown'].includes(r.state)))throw new Error('Existing account holds must be reconciled before a native acceptance launch')
const runtimeRoot=process.argv.includes('--selected')?join(root,'generations',JSON.parse(readFileSync(join(root,'plugin-activation.json'),'utf8')).activeGeneration):root
const store=new QuestStore(ledger),project=projectIdentity(dir)
const q=store.create({id:'01j00000000000000000000997',title:'Astra capability recovery acceptance',objective:'Verify execution and continuation',description:'Isolated real native worker acceptance. Only task-owned fixtures and harmless shell checks are authorized.',contractVersion:2,project,stages:[{id:'capability',title:'Write, read and execute a harmless check',detail:'First report actual agent/provider/model/reasoning/workspace and available editing and shell tools. Load skills help-i-cant-work-right and workspace-flow to verify discovery. Write capability.txt containing ASTRA_CAPABILITY_OK using an available native editing tool (patch, edit, or write; patch is sufficient), read it back, and run a harmless native shell command that verifies the file content and prints ASTRA_SHELL_OK. Write result.json with observed identity, commands and actual results. Mark this step done only after successful write/read/shell verification using quest update, otherwise blocked. No worker spawning.',status:'pending',needs:[]},{id:'followup',title:'Verify the completed worker output',commandID:'verify',status:'pending',needs:['capability']}]})
let calls=0,discovered=false
const server=Bun.serve({port:0,async fetch(request){const p=await request.json() as any;calls++;const tools=p.tools??[],results=(p.messages??[]).filter((m:any)=>m.role==='tool');discovered ||= JSON.stringify(p).includes('help-i-cant-work-right');let chunks:any[]
if(tools.length&&!results.length){const code=`return await tools.quest({action:'run',id:'${q.id}',run:{model:'${model}',continue:true,files:['capability.txt','result.json'],stepIDs:['capability','followup']}})`;chunks=[{id:'fixture',object:'chat.completion.chunk',model:'model',choices:[{index:0,delta:{role:'assistant',tool_calls:[{index:0,id:'launch',type:'function',function:{name:'execute',arguments:JSON.stringify({code})}}]},finish_reason:'tool_calls'}]}]}
else {if(tools.length){const deadline=Date.now()+240000;while(Date.now()<deadline){const actual=store.read(q.id);if((actual?.stages.every(s=>s.status==='done')||actual?.stages.some(s=>s.status==='blocked'))&&actual.sessions.every(s=>['completed','failed','cancelled'].includes(s.state)))break;const file=join(store.runtime,'continuations.json');if(existsSync(file)&&JSON.parse(readFileSync(file,'utf8')).some((x:any)=>x.state==='stopped'))break;await Bun.sleep(200)}}chunks=[{id:'fixture',object:'chat.completion.chunk',model:'model',choices:[{index:0,delta:{content:'FIXTURE_COORDINATOR_DONE'},finish_reason:'stop'}]}]}
return new Response(chunks.map(c=>'data: '+JSON.stringify(c)+'\n\n').join('')+'data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})}})
const config=parse(readFileSync(join(root,'opencode.jsonc'),'utf8')),policy=JSON.parse(readFileSync(join(root,'models/dispatch-policy.json'),'utf8'))
policy.bootstrapByProject={};policy.commandsByProject={[project.id]:{verify:{description:'Verify native worker fixture output',argv:[process.execPath,'-e',"const fs=require('fs');if(fs.readFileSync('capability.txt','utf8').trim()!=='ASTRA_CAPABILITY_OK')process.exit(1);JSON.parse(fs.readFileSync('result.json','utf8'));console.log('CONTINUATION_VERIFIED')"],timeoutMilliseconds:5000}}}
writeFileSync(join(dir,'dispatch-policy.json'),JSON.stringify(policy))
mkdirSync(join(dir,'models'));cpSync(join(root,'models/access-policy.json'),join(dir,'models/access-policy.json'));mkdirSync(join(dir,'plugin'));const url=(p:string)=>JSON.stringify(pathToFileURL(join(runtimeRoot,p)).href)
writeFileSync(join(dir,'plugin/package.json'),JSON.stringify({name:'capability-fixture',version:'1.0.0',main:'index.ts',type:'module'}))
writeFileSync(join(dir,'plugin/index.ts'),`import quests from ${url('quest/server.ts')};export default quests;`)
cpSync(join(root,'skills/help-i-cant-work-right'),join(dir,'skills/help-i-cant-work-right'),{recursive:true})
cpSync(join(root,'skills/workspace-flow'),join(dir,'skills/workspace-flow'),{recursive:true})
config.plugin=['./plugin'];config.mcp={};config.agents={'astra':config.agents.astra};config.providers={openai:config.providers.openai,'coordinator-fixture':{package:'@opencode-ai/ai/providers/openai-compatible',env:[],settings:{baseURL:'http://127.0.0.1:'+server.port+'/v1',apiKey:'fixture-only'},models:{model:{limit:{context:128000,output:2000}}}}}
writeFileSync(join(dir,'opencode.jsonc'),JSON.stringify(config))
writeFileSync(join(dir,'quest-settings.json'),JSON.stringify({version:1,workspaceMode:shared?'shared':'worktree'}))
const preparation=process.argv.includes('--prepared')?new QuestWorkspaces(store.runtime).prepare({directory:dir}):undefined
if(preparation&&preparation.state!=='ready')throw new Error('Prepared fixture unavailable: '+JSON.stringify(preparation))
const proc=Bun.spawn([resolveHostExecutable(),'run','--standalone','--auto','--agent','general','-m','coordinator-fixture/model','Run the existing isolated capability Quest.'],{cwd:dir,env:{...process.env,OPENCODE_CONFIG_DIR:dir,OPENCODE_QUEST_SETTINGS:join(dir,'quest-settings.json'),OPENCODE_CONFIG_PROJECT_DISABLE:'1',OPENCODE_QUEST_ROOT:ledger,OPENCODE_DISPATCH_POLICY:join(dir,'dispatch-policy.json'),OPENCODE_ORCHESTRATION_LEDGER:join(dir,'orchestration.jsonl'),OPENCODE_DISABLE_AUTOUPDATE:'1'},windowsHide:true,stdin:'ignore',stdout:'pipe',stderr:'pipe'})
const timer=setTimeout(()=>proc.kill(),300000)
try{const [code,out,err]=await Promise.all([proc.exited,new Response(proc.stdout).text(),new Response(proc.stderr).text()]);const actual=store.read(q.id)!,run=actual.sessions.find(s=>s.role!=='command'&&s.providerID==='openai');const db=new Database(join(homedir(),'.local/share/opencode/opencode.db'),{readonly:true});const rows=run?db.query('select type,data from session_message where session_id=?').all(run.openCodeSessionId??run.sessionID) as any[]:[];const observed=rows.filter(r=>r.type==='assistant').map(r=>JSON.parse(r.data));db.close();const parts=observed.flatMap(r=>r.content??[]);const workspace=String(run?.scope?.worktree??'');const checks={shared:!shared||(resolve(workspace)===resolve(dir)&&!existsSync(join(dir,'.claude/worktrees'))),prepared:!preparation||!!new QuestWorkspaces(store.runtime).get(run?.runID??'unknown')?.physicalRunID,workspaceSkill:parts.some(p=>p.name==='skill'&&p.state?.status==='completed'&&JSON.stringify(p).includes('workspace-flow')),host:code===0,exact:run?.model===model,role:observed.some(r=>r.agent==='astra'&&r.model?.providerID==='openai'&&r.model?.id==='gpt-6-astra'&&r.model?.variant==='medium'),write:parts.some(p=>['write','edit','patch'].includes(p.name)&&p.state?.status==='completed'),read:parts.some(p=>p.name==='read'&&p.state?.status==='completed'),shell:parts.some(p=>['shell','bash'].includes(p.name)&&p.state?.status==='completed'),skill:parts.some(p=>p.name==='skill'&&p.state?.status==='completed'&&JSON.stringify(p).includes('help-i-cant-work-right')),fixture:existsSync(join(workspace,'capability.txt'))&&readFileSync(join(workspace,'capability.txt'),'utf8').trim()==='ASTRA_CAPABILITY_OK',result:existsSync(join(workspace,'result.json')),steps:actual.stages.every(s=>s.status==='done'),continuation:actual.sessions.some(s=>s.agentRole==='command'&&s.state==='completed')};const ok=Object.values(checks).every(Boolean);writeFileSync(join(dir,'report.json'),JSON.stringify({ok,checks,code,out,err,quest:actual,observed,source:root,runtimeRoot,discovered,preparation,shared},null,2));console.log(JSON.stringify({ok,checks,report:join(dir,'report.json')}));process.exitCode=ok?0:1}finally{clearTimeout(timer);server.stop(true)}
