/** Parent-run exact-Astra acceptance. Do not run while the implementation worker holds the account. */
import {mkdirSync,writeFileSync,readFileSync,existsSync} from 'node:fs'
import {join,resolve} from 'node:path'
import {homedir} from 'node:os'
import {pathToFileURL} from 'node:url'
import JSON5 from 'json5'
import {QuestStore} from '../quest/store'
import {projectIdentity,physicalDirectory} from '../quest/project'
import {runArgv,hostExecutable} from '../project-router/host'
import {createHash} from 'node:crypto'
const root=resolve(import.meta.dir,'..'),dir=join(root,'.visual-e2e','project-router-goal-'+Date.now()),shared=process.argv.includes('--shared'),runtimeIndex=process.argv.indexOf('--runtime-root'),runtimeRoot=runtimeIndex>=0?resolve(process.argv[runtimeIndex+1]):root
const holds=join(homedir(),'.opencode','.quest-runtime','route-reservations.json')
const accessPolicy=join(runtimeRoot,'models','access-policy.json'),accessBytes=readFileSync(accessPolicy)
if(!readFileSync(join(runtimeRoot,'models','dispatch-planner.ts'),'utf8').includes('OPENCODE_ROUTE_RESERVATIONS'))throw new Error('Runtime does not support shared atomic route-reservation pin; no isolated-ledger dispatch is allowed')
if(existsSync(holds)&&JSON.parse(readFileSync(holds,'utf8')).reservations.some((r:any)=>['active','unknown'].includes(r.state)))throw new Error('Active or unknown account ownership exists; parent must reconcile before this exact-route acceptance')
mkdirSync(join(dir,'fixture-plugin'),{recursive:true})
writeFileSync(join(dir,'AGENTS.md'),'Isolated project-router goal acceptance. Edit only marker.txt. Do not create Quests, spawn workers, change source, or contact external resources. Use project_goal for only your assigned steps and project_verify for configured check. Inspect the output, exitCode and timedOut returned by project_verify; its durable log path is not an instruction to read outside this workspace. No additional log-read permission is needed. If returned evidence is insufficient, stop blocked for parent inspection.\n')
writeFileSync(join(dir,'.gitignore'),'ledger/\nfixture-plugin/\n*.json\n*.jsonc\n*.jsonl*\n.claude/\n')
for(const args of [['init',dir],['-C',dir,'add','AGENTS.md','.gitignore'],['-C',dir,'-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','Goal fixture']])if((await runArgv('git',args)).code!==0)throw new Error('Fixture Git failed')
const ledger=join(dir,'ledger'),store=new QuestStore(ledger),project=projectIdentity(dir),id='01j00000000000000000000996',model='openai/gpt-6-astra#medium'
store.create({id,title:'Assigned goal live trigger',objective:'Verify two real worker turns and assigned proof',description:'Explicit two-turn same-session goal acceptance',contractVersion:2,project,extensions:{routerVerification:{goal:'verify'}},stages:[{id:'goal',title:'Verify assigned goal',detail:'First turn: call usage_status format=json and report actual provider/model/reasoning plus exposed read/edit/shell capabilities. Require exact openai/gpt-6-astra#medium; otherwise stop blocked. Call project_goal action=start with this Quest ID and stepIDs [goal], then finish the turn with GOAL_FIRST_TURN without marking the step done. On the automatic same-session followup only: write marker.txt containing GOAL_WORKER_OK with a native editing tool, call project_verify action=run with this Quest ID, stepID goal, commandID verify, then update only assigned step goal to done with the actual check result. Do not dispatch workers or create Quests. If continuation, ownership, model or proof fails, report blocked.',status:'pending',needs:[]}]})
const observations:any[]=[]
let waitOutcome='not-started'
const admissionCode=`const usage=await tools.usage_status({format:'json',refresh:true});const route=await tools.project_route_status({model:'${model}'});const account=usage.accounts.find(a=>a.id===route.account?.id);if(route.code!=='ROUTE_CONFIGURED'||!account||account.state!=='available'||account.freshness?.stale)return {prelaunch:true,route,usageAt:usage.updatedAt};const observedUsage={updatedAt:usage.updatedAt,accountID:account.id,state:account.state,freshness:account.freshness};try{const run=await tools.quest({action:'run',id:'${id}',run:{model:'${model}',stepIDs:['goal'],files:['marker.txt']}});return {usage:observedUsage,route,run}}catch(error){return {usage:observedUsage,route,error:String(error)}}`
const provider=Bun.serve({port:0,async fetch(request){
 const body=await request.json() as any,tools=body.tools??[],results=(body.messages??[]).filter((m:any)=>m.role==='tool')
 const names=tools.map((t:any)=>t.function?.name??t.name),capabilities={read:names.includes('read'),editing:names.some((n:string)=>['write','edit','patch'].includes(n)),shell:names.includes('shell'),codeMode:names.includes('execute')}
 observations.push({capabilities,scope:'actual coordinator model-facing catalog; worker policy separately checked by its first-turn receipt',results:results.map((r:any)=>r.content)})
  if(results.length&&store.read(id)?.sessions.length){const deadline=Date.now()+240000;waitOutcome='deadline-unknown';while(Date.now()<deadline){const q=store.read(id)!,file=join(store.runtime,'continuations.json'),goals=existsSync(file)?JSON.parse(readFileSync(file,'utf8')):[],reservations=existsSync(holds)?JSON.parse(readFileSync(holds,'utf8')).reservations:[];const terminal=q.sessions.every(s=>['completed','failed','cancelled'].includes(s.state)),released=q.sessions.every(s=>!reservations.some((r:any)=>r.runID===s.runID&&['active','unknown'].includes(r.state)));if(terminal&&released&&q.sessions.every(s=>!s.sessionID&&s.state==='failed')){waitOutcome='prelaunch-failed';break}if(terminal&&released&&goals.some((g:any)=>g.worker&&['done','stopped'].includes(g.state))){waitOutcome='canonical-terminal';break}await Bun.sleep(200)}observations.push({capabilities,results:[],waitOutcome,recovery:waitOutcome==='deadline-unknown'?'Unknown outcome: preserve workspace and ownership, inspect pending permissions with supported host API, then explicitly resume; never auto-retry.':undefined})}
 const delta=tools.length&&!results.length&&Object.values(capabilities).every(Boolean)?{role:'assistant',tool_calls:[{index:0,id:'admit',type:'function',function:{name:'execute',arguments:JSON.stringify({code:admissionCode})}}]}:{content:tools.length&&!results.length?'HOST_CAPABILITY_BLOCKED':'GOAL_COORDINATOR_DONE'}
 return new Response('data: '+JSON.stringify({id:'fixture',object:'chat.completion.chunk',model:'model',choices:[{index:0,delta,finish_reason:'tool_calls' in delta?'tool_calls':'stop'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})
}})
const config=JSON5.parse(readFileSync(join(root,'opencode.jsonc'),'utf8')),policy=JSON.parse(readFileSync(join(runtimeRoot,'models','dispatch-policy.json'),'utf8'))
policy.bootstrapByProject={};policy.commandsByProject={[project.id]:{verify:{description:'Read real worker marker',argv:[process.execPath,'-e',"if(require('fs').readFileSync('marker.txt','utf8').trim()!=='GOAL_WORKER_OK')process.exit(1);console.log('GOAL_VERIFIED')"],timeoutMilliseconds:5000}}}
writeFileSync(join(dir,'dispatch-policy.json'),JSON.stringify(policy));writeFileSync(join(dir,'quest-settings.json'),JSON.stringify({version:1,workspaceMode:shared?'shared':'worktree'}))
const url=(p:string)=>JSON.stringify(pathToFileURL(join(runtimeRoot,p)).href)
writeFileSync(join(dir,'fixture-plugin/package.json'),JSON.stringify({name:'goal-fixture',version:'1.0.0',main:'index.ts',type:'module'}));writeFileSync(join(dir,'fixture-plugin/index.ts'),`import {define} from '@opencode-ai/plugin/v2/promise';import usage from ${url('usage/server.ts')};import quests from ${url('quest/server.ts')};import router from ${url('project-router/server.ts')};export default define({id:'goal-fixture',async setup(ctx){await usage.setup(ctx);await quests.setup(ctx);return router.setup(ctx)}})`)
config.plugin=['./fixture-plugin'];config.mcp={};config.agents={astra:config.agents.astra,general:{permissions:[{action:'*',resource:'*',effect:'allow'}]}};config.providers={openai:config.providers.openai,fixture:{package:'@opencode-ai/ai/providers/openai-compatible',env:[],settings:{baseURL:`http://127.0.0.1:${provider.port}/v1`,apiKey:'fixture-only'},models:{model:{limit:{context:128000,output:2000}}}}};writeFileSync(join(dir,'opencode.jsonc'),JSON.stringify(config))
try{
 const outcome=await runArgv(hostExecutable(),['run','--standalone','--auto','--agent','general','-m','fixture/model','Run the explicitly authorized isolated goal Quest.'],{cwd:dir,timeout:300000,maxBytes:512000,env:{...process.env,OPENCODE_CONFIG_DIR:dir,OPENCODE_CONFIG_PROJECT_DISABLE:'1',OPENCODE_QUEST_ROOT:ledger,OPENCODE_DISPATCH_POLICY:join(dir,'dispatch-policy.json'),OPENCODE_ACCESS_POLICY:accessPolicy,OPENCODE_ROUTE_RESERVATIONS:holds,OPENCODE_QUEST_SETTINGS:join(dir,'quest-settings.json'),OPENCODE_ORCHESTRATION_LEDGER:join(dir,'orchestration.jsonl'),OPENCODE_DISABLE_AUTOUPDATE:'1'}})
 const q=store.read(id)!,file=join(store.runtime,'continuations.json'),goals=existsSync(file)?JSON.parse(readFileSync(file,'utf8')):[],run=q.sessions[0],reservation=existsSync(holds)?JSON.parse(readFileSync(holds,'utf8')).reservations.find((r:any)=>r.runID===run?.runID):undefined
 const checks={host:outcome.code===0,capabilitiesBeforeAdmission:observations.some(o=>Object.values(o.capabilities).every(Boolean)),usageBeforeAdmission:observations.some(o=>o.results.some((r:any)=>typeof r==='string'&&r.includes('"usage"')&&r.includes('"freshness"'))),sharedAtomicAdmission:!!reservation,accessPolicyUnchanged:Buffer.compare(readFileSync(accessPolicy),accessBytes)===0,oneWorker:q.sessions.length===1&&!!run?.sessionID,exact:run?.model===model,goal:goals.some((g:any)=>g.worker&&g.state==='done'&&g.attempt>=1),proof:q.stages[0].proofs.some(p=>p.verified&&p.result==='passed'&&p.command==='verify'),done:q.stages[0].status==='done',terminal:run?.state==='completed',workspace:!!run?.scope?.worktree&&(shared?physicalDirectory(run.scope.worktree)===physicalDirectory(dir):physicalDirectory(run.scope.worktree)!==physicalDirectory(dir))}
  const lifecycleChecks={observedTerminalBeforeExit:waitOutcome==='canonical-terminal',accountSettled:reservation?.state==='settled'}
  const ok=Object.values({...checks,...lifecycleChecks}).every(Boolean);writeFileSync(join(dir,'report.json'),JSON.stringify({ok,checks:{...checks,...lifecycleChecks},waitOutcome,outcome,goals,quest:q,observations,runtimeRoot,shared,reservation,accessPolicySHA256:createHash('sha256').update(accessBytes).digest('hex'),admission:'Normal Quest run, using shared canonical atomic route reservations despite isolated Quest storage'},null,2));console.log(JSON.stringify({ok,checks:{...checks,...lifecycleChecks},path:join(dir,'report.json')},null,2));if(!ok)process.exitCode=1
}catch(error){const message=error instanceof Error?error.message:String(error);writeFileSync(join(dir,'report.json'),JSON.stringify({ok:false,phase:'host-or-acceptance',message,quest:store.read(id),runtimeRoot,shared,reservations:holds,recovery:'Outcome may be unknown. Preserve workspace and shared account reservation; inspect before explicit recovery.'},null,2));console.error(JSON.stringify({ok:false,message,path:join(dir,'report.json')}));process.exitCode=1}finally{provider.stop()}
