import { resolveHostExecutable } from '../project-router/executable.mjs'
/** Actual host session/workspace adapter with a synthetic route and local deterministic provider. */
import {mkdirSync,writeFileSync,readFileSync,existsSync} from "node:fs"
import {join,resolve} from "node:path"
import {pathToFileURL} from "node:url"
import {QuestStore} from "../quest/store"
import {readAllQuests} from "../quest/index"
const paced=process.argv.includes("--paced")
const root=resolve(import.meta.dir,".."),dir=join(root,".visual-e2e","model-worker-host-"+Date.now()),ledger=join(dir,"ledger")
mkdirSync(dir,{recursive:true});writeFileSync(join(dir,".gitignore"),"cache/\ndata/\nstate/\nledger/\n.claude/\n*.db*\n*.jsonl\nprovider-*.json\naccounts.json\n");mkdirSync(join(dir,"empty-auth"));for(const args of [["init",dir],["-C",dir,"add",".gitignore"],["-C",dir,"-c","user.name=Fixture","-c","user.email=fixture@example.invalid","commit","--allow-empty","-m","Fixture base"]]){if(Bun.spawnSync(["git",...args],{windowsHide:true}).exitCode!==0)throw new Error("Fixture Git setup failed")}
const store=new QuestStore(ledger),quest=()=>readAllQuests(ledger,{includeArchived:true}).find(q=>q.quest)?.quest
let calls=0,workerCalls=0,parentResult=false
const chunk=(content:string)=>[{id:"fixture",object:"chat.completion.chunk",model:"model",choices:[{index:0,delta:{content},finish_reason:"stop"}],usage:{prompt_tokens:100,completion_tokens:10,prompt_tokens_details:{cached_tokens:20},completion_tokens_details:{reasoning_tokens:0}}}]
const call=(name:string,input:any)=>[{id:"fixture",object:"chat.completion.chunk",model:"model",choices:[{index:0,delta:{role:"assistant",tool_calls:[{index:0,id:"fixture-"+calls,type:"function",function:{name,arguments:JSON.stringify(input)}}]},finish_reason:null}]},{id:"fixture",object:"chat.completion.chunk",model:"model",choices:[{index:0,delta:{},finish_reason:"tool_calls"}]}]
const server=Bun.serve({port:0,async fetch(request){const p=await request.json() as any;calls++;writeFileSync(join(dir,"provider-"+calls+".json"),JSON.stringify(p));let chunks:any[];const tools=p.tools??[],messages=p.messages??[],results=messages.filter((m:any)=>m.role==="tool"),worker=JSON.stringify(messages).includes("Assigned steps:")
 if(!tools.length)chunks=chunk("Fixture title")
 else if(worker){workerCalls++;const q=quest()!,session=q.sessions.find(s=>s.runID)!,path=String(session.scope?.worktree)
  if(!results.length)chunks=call("write",{path:join(path,"model-output.txt"),content:"Native worker fixture output"})
  else if(results.length===1)chunks=call("execute",{code:"return await tools.quest({action:'update',id:"+JSON.stringify(q.id)+",update:{steps:[{id:'model-step',state:'done',note:'Wrote the fixture file through the native tool'}]}})"})
  else chunks=chunk("WORKER_DONE")
 }else if(!results.length){chunks=call("execute",{code:"const q=await tools.quest({action:'create',create:{title:'Native worker fixture',description:'Verify actual worker binding',steps:[{id:'model-step',title:'Write the fixture output'}]}});const run=await tools.quest({action:'run',id:q.id,run:{model:'worker-fixture/model'}});return {marker:'ROOT_STARTED',id:q.id,run};"})}
 else {parentResult=results.some((m:any)=>String(m.content).includes("ROOT_STARTED"));const deadline=Date.now()+20000;while(parentResult&&Date.now()<deadline&&!quest()?.sessions.some(s=>s.state==="completed"))await Bun.sleep(50);chunks=chunk(parentResult?"ROOT_DONE":"ROOT_FAILED")}
 return new Response(chunks.map(c=>"data: "+JSON.stringify(c)+"\n\n").join("")+"data: [DONE]\n\n",{headers:{"content-type":"text/event-stream"}})
}})
const plugin=join(dir,"plugin");mkdirSync(plugin);const url=(p:string)=>JSON.stringify(pathToFileURL(join(root,p)).href)
writeFileSync(join(plugin,"package.json"),JSON.stringify({name:"worker-fixture",version:"1.0.0",main:"index.ts",type:"module"}))
const fixturePolicy=join(dir,"dispatch-policy.json"),fixtureAccount={id:"fixture-account",provider:"openai",plan:{name:"fixture",rateLimitTier:null,multiplier:null,provenance:"provider-observed",observedAt:new Date().toISOString()},state:"available",observedAt:new Date().toISOString(),connections:[{owner:"opencode",routeProviders:["worker-fixture"],modelPrefix:null}],windows:[{id:"shared",scope:"shared",label:"Fixture pool",state:"available",usedPercent:0,observedAt:new Date().toISOString(),remainingPercent:100,resetAt:new Date(Date.now()+3600000).toISOString()}]}
writeFileSync(fixturePolicy,JSON.stringify({version:1,request:{task:"coding",minSuccessRate:0.9,minTrials:5,qualityTolerance:0.02,maxUsageAgeSeconds:120,maxEvidenceAgeDays:30,maxCashPerSuccess:0,reserveFraction:0,allowedRouteIDs:["fixture"]},routes:[{id:"fixture",accountID:"fixture-account",providerID:"worker-fixture",modelID:"model",harness:"native",agent:"general",reasoning:"unknown",serviceTier:"default",verified:true,admission:"configured-choice",evidence:[],quotaPerTask:{}}],billing:{"fixture-account":"subscription"},bootstrapByProject:{}}))
mkdirSync(join(dir,"models"));writeFileSync(join(dir,"models","access-policy.json"),JSON.stringify({version:1,routes:[{providerID:"worker-fixture",modelPattern:"model",transports:[{origin:"http://127.0.0.1:"+server.port,pathPrefix:"/v1/"}]}]}))
const pacingSetup=paced?"import {setUsageTarget} from "+url("usage/usage-target.ts")+";import {accountRegime} from "+url("usage/calibration-store.ts")+";import {assertBurnLaunchAllowed} from "+url("usage/burn-control.ts")+";const fixtureAccount="+JSON.stringify(fixtureAccount)+";const fixtureUsage=async()=>({schema:1,updatedAt:new Date().toISOString(),accounts:[{...fixtureAccount,observedAt:new Date().toISOString(),windows:fixtureAccount.windows.map(w=>({...w,observedAt:new Date().toISOString()}))}],diagnostics:[]});setUsageTarget(fixtureAccount.id,Date.now()+60000,0,undefined,Date.now(),{windowID:'shared',regime:accountRegime(fixtureAccount),resetAt:Date.parse(fixtureAccount.windows[0].resetAt),maxConcurrent:4});":""
writeFileSync(join(plugin,"index.ts"),pacingSetup+"import {reserveDispatch} from "+url("models/dispatch-planner.ts")+"; import quests from "+url("quest/server.ts")+"; import usage from "+url("usage/server.ts")+"; import {QuestStore} from "+url("quest/store.ts")+"; import {typedQuestTool} from "+url("quest/typed-tool.ts")+"; import {startQuestRun} from "+url("quest/runtime.ts")+"; export default {id:'native-worker-fixture',async setup(ctx){await quests.setup(ctx);await usage.setup(ctx);const store=new QuestStore("+JSON.stringify(ledger)+");await ctx.tool.transform(draft=>draft.update('quest',tool=>Object.assign(tool,typedQuestTool(store,ctx.session,{startRun:startQuestRun(store,ctx.session,{policyFile:'fixture-only',"+(paced?"beforePrompt:id=>assertBurnLaunchAllowed(id,fixtureUsage),":"")+"reserve:async(input)=>reserveDispatch({...input,policyFile:"+JSON.stringify(fixturePolicy)+"},"+(paced?"fixtureUsage":"async()=>({schema:1,updatedAt:new Date().toISOString(),accounts:["+JSON.stringify(fixtureAccount)+"],diagnostics:[]})")+")})}))));}}")
writeFileSync(join(dir,"opencode.jsonc"),JSON.stringify({plugin:["./plugin"],providers:{"worker-fixture":{package:"@opencode-ai/ai/providers/openai-compatible",env:[],settings:{baseURL:"http://127.0.0.1:"+server.port+"/v1",apiKey:"fixture-only"},models:{model:{limit:{context:128000,output:1000}}}}}}))
const telemetry=join(dir,"requests.jsonl"),proc=Bun.spawn([resolveHostExecutable(),"run","--standalone","--agent","general","-m","worker-fixture/model","Run the native worker fixture"],{cwd:dir,env:{...process.env,OPENCODE_ORCHESTRATION_LEDGER:join(dir,"orchestration.jsonl"),OPENCODE_CAPACITY_FILE:join(dir,"capacity.json"),OPENCODE_QUEST_SETTINGS:join(dir,"quest-settings.json"),CODEX_HOME:join(dir,"empty-codex"),OPENCODE_CONFIG_DIR:dir,OPENCODE_CONFIG_PROJECT_DISABLE:"1",OPENCODE_QUEST_ROOT:ledger,OPENCODE_ACCOUNT_DISCOVERY_ROOT:join(dir,"empty-auth"),OPENCODE_ACCOUNT_USAGE_FILE:join(dir,"accounts.json"),OPENCODE_TELEMETRY_FILE:telemetry,OPENCODE_DB:join(dir,"host.db"),XDG_DATA_HOME:join(dir,"data"),XDG_STATE_HOME:join(dir,"state"),XDG_CACHE_HOME:join(dir,"cache"),OPENCODE_DISABLE_AUTOUPDATE:"1"},stdin:"ignore",stdout:"pipe",stderr:"pipe",windowsHide:true})
const timer=setTimeout(()=>proc.kill(),60000)
try{const[code,out,err]=await Promise.all([proc.exited,new Response(proc.stdout).text(),new Response(proc.stderr).text()]),q=quest();const records=readFileSync(telemetry,"utf8").trim().split("\n").map(line=>JSON.parse(line).request);const session=q?.sessions.find(s=>s.runID);const workspace=session?.runID&&existsSync(join(store.runtime,"workspaces",session.runID+".json"))?JSON.parse(readFileSync(join(store.runtime,"workspaces",session.runID+".json"),"utf8")):null;const reservation=session?.runID&&existsSync(join(store.runtime,"route-reservations.json"))?JSON.parse(readFileSync(join(store.runtime,"route-reservations.json"),"utf8")).reservations.find((r:any)=>r.runID===session.runID):undefined;const checks={configuredAdmission:(paced?reservation?.paced===true&&reservation?.exclusive===false:reservation?.exclusive===true)&&reservation?.state==="settled"&&session?.routingNote?.includes("uncalibrated")===true,host:code===0,parentResult,worker:workerCalls>=2,completed:session?.state==="completed",step:q?.stages[0].status==="done",changes:workspace?.changes?.files.some((f:any)=>f.path==="model-output.txt")===true,telemetry:records.some(r=>r.questID===q?.id&&r.parentID===session?.parentID&&r.sessionID===session?.sessionID)};const ok=Object.values(checks).every(Boolean);writeFileSync(join(dir,"report.json"),JSON.stringify({ok,checks,calls,workerCalls,code,out,err,quest:q,workspace},null,2));console.log(JSON.stringify({ok,checks,report:join(dir,"report.json")}));process.exitCode=ok?0:1}finally{clearTimeout(timer);server.stop(true)}
