import {readFileSync} from "node:fs"
import {join} from "node:path"
import {homedir} from "node:os"
import {verifyOAuthProxy} from "./subscription-policy"
export type AccessPolicy={version:1;routes:{providerID:string;modelPattern:string;verifyOAuthBroker?:boolean;transports:{origin:string;pathPrefix:string}[]}[]}
export function configuredAccess():AccessPolicy{let policy:AccessPolicy;try{policy=JSON.parse(readFileSync(process.env.OPENCODE_ACCESS_POLICY??join(process.env.OPENCODE_CONFIG_DIR??join(homedir(),".config","opencode"),"models","access-policy.json"),"utf8"))}catch{throw new Error("Access policy is unavailable; configure allowed routes and transports before sending requests")};if(policy.version!==1||!Array.isArray(policy.routes)||!policy.routes.length)throw new Error("Invalid access policy; no requests authorized");return policy}
export function assertConfiguredModel(model:{providerID:string;id?:string;modelID?:string},policy=configuredAccess()){const id=model.id??model.modelID;if(!model.providerID||!id)throw new Error("Exact model identity is required");const route=policy.routes.find(r=>r.providerID===model.providerID&&new RegExp("^(?:"+r.modelPattern+")$").test(id));if(!route)throw new Error("User access policy does not allow "+model.providerID+"/"+id);return route}
export function assertConfiguredRequest(model:{providerID:string;id?:string;modelID?:string},requestURL:string,policy=configuredAccess()){const route=assertConfiguredModel(model,policy),url=new URL(requestURL);if(!route.transports.some(t=>url.origin===t.origin&&url.pathname.startsWith(t.pathPrefix)))throw new Error("Request transport is not allowed by user access policy for "+model.providerID);return route}
export async function installAccessGuard(ctx:{session?:{hook?:Function}}){if(typeof ctx.session?.hook!=="function")throw new Error("Cannot install configured access policy");configuredAccess();await ctx.session.hook("http.request",(event:any)=>{const route=assertConfiguredRequest(event.model,event.request.url);if(route.verifyOAuthBroker&&new URL(event.request.url).origin!==verifyOAuthProxy().origin)throw new Error("Configured broker origin does not match its verified endpoint")})}
