import {existsSync,readFileSync} from "node:fs"
import {dirname,join} from "node:path"
import {AdaptiveContextRuntime} from "./context-runtime"
import {configuredDispatchPolicyFile} from "./dispatch-planner"
import {readAllQuests} from "../quest/index"
import {questRoot} from "../quest/root"
import {TELEMETRY_FILE} from "../usage/telemetry-api"
const text={type:"string"},strings={type:"array",items:text},number={type:"number",minimum:0}
export async function installAdaptiveContext(ctx:any){
 const settings=()=>{const file=configuredDispatchPolicyFile();return existsSync(file)?JSON.parse(readFileSync(file,"utf8")).context:undefined}
 const compact=typeof ctx.session?.compact==="function"?async(input:{sessionID:string;checkpointID:string})=>{const result=await ctx.session.compact({sessionID:input.sessionID}),record=result?.data??result;if(record?.sessionID!==input.sessionID||record?.type!=="compaction"||typeof record?.id!=="string")throw Error("Host did not return a compaction admission receipt");return {receipt:record.id}}:undefined
 const runtime=new AdaptiveContextRuntime(join(dirname(TELEMETRY_FILE),"context"),{policy:()=>settings()?.policy,headroom:()=>settings()?.headroom,compact,pendingWorkers:sessionID=>{const rows=readAllQuests(questRoot());if(rows.some(r=>r.errors.length))throw Error("Pending worker state is unreadable; context retained");return rows.flatMap(q=>q.quest?.sessions??[]).filter(s=>(s.parentID??s.parentSessionID)===sessionID&&["planned","executing","waiting","blocked"].includes(s.state)).length},routeLimit:async sessionID=>{const response=await ctx.session.get({sessionID}),session=response?.data??response,list=await ctx.catalog?.model?.list(),models=list?.data??list,model=Array.isArray(models)?models.find(m=>m.providerID===session?.model?.providerID&&m.id===session?.model?.id):undefined;return Number.isFinite(model?.limit?.context)?model.limit.context:undefined}})
 if(ctx.session?.hook)await ctx.session.hook("context",(event:any)=>{if(!event.sessionID||!Array.isArray(event.system))return;const text=runtime.checkpointText(event.sessionID);if(text)event.system.push({type:"text",text})})
 if(ctx.tool?.hook)for(const name of ["execute.before","execute.after"])await ctx.tool.hook(name,(event:any)=>{const id=event.id??event.callID;if(event.sessionID&&id)runtime.tool(event.sessionID,id,name==="execute.before")})
 if(ctx.event?.subscribe){const stream=await ctx.event.subscribe({});void(async()=>{for await(const event of stream)try{await runtime.event(event)}catch(error){console.error("[models] Context event retained with error",error instanceof Error?error.message:"unknown error")}})().catch(error=>console.error("[models] Adaptive context events failed",error instanceof Error?error.message:"unknown error"))}
 if(ctx.tool?.transform)await ctx.tool.transform((draft:any)=>draft.add({name:"context_checkpoint",description:"Inspect or preserve recoverable task context. Prepare records corrections, permissions, unresolved work and history. Forecasts are estimates. Compaction waits for a safe boundary and requires supported host admission; no context limit is invented.",input:{type:"object",properties:{action:{type:"string",enum:["inspect","prepare","retain","compact"]},reason:text,context:{type:"object",properties:{intent:text,corrections:strings,permissions:strings,decisions:strings,unresolved:strings,questIDs:strings,pendingResults:strings,historyReferences:strings,nextVerification:strings,workspace:{type:"object",properties:{directory:text,branch:text,uncommittedChanges:strings},required:["directory","uncommittedChanges"],additionalProperties:false}},required:["intent","corrections","permissions","decisions","unresolved","questIDs","pendingResults","historyReferences","nextVerification"],additionalProperties:false},forecast:{type:"object",properties:{currentTokens:number,retainedTokens:number,remainingInputs:number,cacheHitFraction:number,retainedCacheHitFraction:number,uncachedUnitCost:number,cachedUnitCost:number,checkpointCost:number,retrievalCost:number,qualityRisk:number,costUnit:text},required:["currentTokens","retainedTokens","remainingInputs","cacheHitFraction","retainedCacheHitFraction","uncachedUnitCost","cachedUnitCost","checkpointCost","retrievalCost","qualityRisk","costUnit"],additionalProperties:false}},required:["action"],additionalProperties:false},output:{type:"object",additionalProperties:true},execute:async(input:any,context:any)=>{if(!context?.sessionID)throw Error("Host session identity required");let result:any;if(input.action==="prepare"){if(!input.context||!input.forecast||!input.reason)throw Error("Prepare requires context, forecast and reason");result=runtime.prepare(context.sessionID,input.context,input.forecast,input.reason)}else if(input.action==="retain"||input.action==="compact")result=await runtime.choose(context.sessionID,input.action);else if(input.action==="inspect")result=runtime.inspect(context.sessionID);else throw Error("Unknown context action");const content=JSON.stringify(result);return {output:JSON.parse(content),content}}}))
 return runtime
}
