import { createHash,randomUUID } from "node:crypto"
import { existsSync,mkdirSync,readFileSync,writeFileSync,renameSync } from "node:fs"
import { join,dirname } from "node:path"
import { acquireLock } from "../quest/locking"
export type ContextForecast = { currentTokens:number; retainedTokens:number; remainingInputs:number; cacheHitFraction:number; retainedCacheHitFraction:number; uncachedUnitCost:number; cachedUnitCost:number; checkpointCost:number; retrievalCost:number; qualityRisk:number; costUnit:string }
export type ContextPolicy = { automatic:boolean; minSavings:number; maxQualityRisk:number; minNewTokensSinceCompaction:number }
export type ContextBoundary = { safe:boolean; pendingTools:number; pendingWorkerResults:number; revision:number; checkpointRevision:number; newlyAddedTokens:number; userChoice?:"compact"|"retain"; verifiedRouteLimit?:number; requiredOutputTokens:number; toolHeadroomTokens:number }
export function decideContext(f:ContextForecast,b:ContextBoundary,p:ContextPolicy) {
 if(![b.pendingTools,b.pendingWorkerResults,b.revision,b.checkpointRevision,b.newlyAddedTokens,b.requiredOutputTokens,b.toolHeadroomTokens,p.minSavings,p.maxQualityRisk,p.minNewTokensSinceCompaction].every(n=>Number.isFinite(n)&&n>=0)||typeof b.safe!=="boolean"||typeof p.automatic!=="boolean"||p.maxQualityRisk>1||b.verifiedRouteLimit!==undefined&&(!Number.isFinite(b.verifiedRouteLimit)||b.verifiedRouteLimit<=0))throw new Error("Invalid context boundary or policy")
 const invalid=Object.values(f).some(v=>typeof v==="number"&&(!Number.isFinite(v)||v<0))||f.cacheHitFraction>1||f.retainedCacheHitFraction>1||f.retainedTokens>f.currentTokens||f.qualityRisk>1||!f.costUnit
 if(invalid)throw new Error("Invalid context forecast")
 const cost=(tokens:number,hit:number)=>tokens*((1-hit)*f.uncachedUnitCost+hit*f.cachedUnitCost)
 const retainCost=f.remainingInputs*cost(f.currentTokens,f.cacheHitFraction),compactCost=f.checkpointCost+f.retrievalCost+f.remainingInputs*cost(f.retainedTokens,f.retainedCacheHitFraction),savings=retainCost-compactCost
 const base={retainCost,compactCost,savings,costUnit:f.costUnit,qualityRisk:f.qualityRisk}
 const overflow=b.verifiedRouteLimit!==undefined&&f.currentTokens+b.requiredOutputTokens+b.toolHeadroomTokens>b.verifiedRouteLimit
 if(!b.safe||b.pendingTools>0||b.pendingWorkerResults>0)return {...base,action:"wait" as const,reason:"Finish pending tool and worker interactions before changing context",overflow}
 if(b.revision!==b.checkpointRevision)return {...base,action:"checkpoint" as const,reason:"Checkpoint does not include the latest corrections and permissions",overflow}
 if(b.userChoice==="retain"&&!overflow)return {...base,action:"retain" as const,reason:"User requested retaining context",overflow}
 if(overflow)return {...base,action:"compact" as const,reason:"Measured input plus required headroom exceeds the verified route limit",overflow}
 if(f.qualityRisk>p.maxQualityRisk)return {...base,action:"retain" as const,reason:"Checkpoint quality risk exceeds policy",overflow}
 if(b.userChoice==="compact")return {...base,action:"compact" as const,reason:"User requested compaction at a safe boundary",overflow}
 if(!p.automatic)return {...base,action:"retain" as const,reason:"Automatic context changes are disabled",overflow}
 if(b.newlyAddedTokens<p.minNewTokensSinceCompaction)return {...base,action:"retain" as const,reason:"Too little new context since the last checkpoint",overflow}
 return {...base,action:savings>p.minSavings?"compact" as const:"retain" as const,reason:savings>p.minSavings?"Expected repeated-input savings exceed checkpoint, cache-loss and retrieval costs":"Retaining context has lower cost under the current forecast",overflow}
}
export type RecoverableContext = { revision:number; intent:string; corrections:string[]; permissions:string[]; decisions:string[]; unresolved:string[]; questIDs:string[]; pendingResults:string[]; historyReferences:string[]; workspace?:{directory:string;branch?:string;uncommittedChanges:string[]}; nextVerification:string[] }
export type Checkpoint = { id:string;sessionID:string;createdAt:number;reason:string;context:RecoverableContext;hash:string;state:"prepared"|"requested"|"active"|"failed"|"superseded";hostReceipt?:string;error?:string;beforeTokens?:number;afterTokens?:number }
export class ContextCheckpoints {
 constructor(readonly directory:string){}
 private file(sessionID:string){if(!/^[a-zA-Z0-9_-]{1,150}$/.test(sessionID))throw new Error("Invalid context session identity");return join(this.directory,sessionID+".json")}
 read(sessionID:string):Checkpoint[]{const file=this.file(sessionID);if(!existsSync(file))return [];const rows=JSON.parse(readFileSync(file,"utf8"));if(!Array.isArray(rows))throw new Error("Unreadable context history; preserve it before retrying");return rows}
 private update(sessionID:string,fn:(rows:Checkpoint[])=>Checkpoint){const file=this.file(sessionID),lock=acquireLock(dirname(file),"context-"+sessionID);try{const rows=this.read(sessionID),result=fn(rows);mkdirSync(dirname(file),{recursive:true});const tmp=file+"."+process.pid+".tmp";writeFileSync(tmp,JSON.stringify(rows),{mode:0o600});renameSync(tmp,file);return result}finally{lock.release()}}
 prepare(sessionID:string,context:RecoverableContext,reason:string,beforeTokens?:number){if(!context||[context.corrections,context.permissions,context.decisions,context.unresolved,context.questIDs,context.pendingResults,context.historyReferences,context.nextVerification].some(items=>!Array.isArray(items)||items.some(item=>typeof item!=="string")))throw new Error("Checkpoint lists must contain text");if(!Number.isInteger(context.revision)||context.revision<0||!context.intent.trim()||!context.historyReferences.length||!reason.trim())throw new Error("Checkpoint requires revision, intent, recoverable history and reason");if(context.pendingResults.length)throw new Error("Retain context until pending results are collected");const value:Checkpoint={id:randomUUID(),sessionID,createdAt:Date.now(),reason,context:structuredClone(context),hash:createHash("sha256").update(JSON.stringify(context)).digest("hex"),state:"prepared",beforeTokens};return this.update(sessionID,rows=>{rows.push(value);return value})}
 async request(checkpoint:Checkpoint,currentRevision:number,compact?: (input:{sessionID:string;checkpointID:string})=>Promise<{receipt:string}>){if(!compact)throw new Error("Host compaction adapter is unavailable; context was retained");if(currentRevision!==checkpoint.context.revision)throw new Error("New corrections supersede this checkpoint; prepare a current one");const prior=this.read(checkpoint.sessionID).find(c=>c.id===checkpoint.id);if(!prior||prior.hash!==checkpoint.hash)throw new Error("Checkpoint identity mismatch");if(prior.state!=="prepared")throw new Error("Compaction already requested; reconcile before retrying")
 this.update(checkpoint.sessionID,rows=>{const c=rows.find(c=>c.id===checkpoint.id)!;if(c.state!=="prepared")throw new Error("Compaction already requested; reconcile before retrying");c.state="requested";return c})
 try{const result=await compact({sessionID:checkpoint.sessionID,checkpointID:checkpoint.id});if(!result.receipt)throw new Error("Host did not confirm receipt; inspect the existing request before retrying");return this.update(checkpoint.sessionID,rows=>{const c=rows.find(c=>c.id===checkpoint.id)!;c.hostReceipt=result.receipt;return c})}catch(e){this.update(checkpoint.sessionID,rows=>{const c=rows.find(c=>c.id===checkpoint.id)!;c.error=e instanceof Error?e.message:String(e);return c});throw e}
 }
 measureAfter(sessionID:string,id:string,tokens:number){if(!Number.isFinite(tokens)||tokens<0)throw new Error("Invalid observed context");return this.update(sessionID,rows=>{const c=rows.find(c=>c.id===id);if(!c||c.state!=="active")throw new Error("No active checkpoint to measure");c.afterTokens??=tokens;return c})}
 confirm(sessionID:string,id:string,input:{currentRevision:number;hostReceipt:string;afterTokens?:number;success:boolean}){return this.update(sessionID,rows=>{const c=rows.find(c=>c.id===id);if(!c||c.state!=="requested"||c.hostReceipt!==input.hostReceipt)throw new Error("No matching host compaction receipt");if(input.afterTokens!==undefined&&(!Number.isFinite(input.afterTokens)||input.afterTokens<0))throw new Error("Invalid observed context");c.state=input.currentRevision!==c.context.revision?"superseded":input.success?"active":"failed";c.afterTokens=input.afterTokens;return c})}
}
/** Verified host HTTP route. Supply its authenticated transport; never invent an SDK compact method. */
export function hostCompactionAdapter(baseURL:string,transport:typeof fetch=fetch){const url=new URL(baseURL);if(!["127.0.0.1","localhost","[::1]"].includes(url.hostname)||!["http:","https:"].includes(url.protocol))throw new Error("Compaction adapter requires the owning local host endpoint");return async(input:{sessionID:string;checkpointID:string})=>{const response=await transport(new URL("/api/session/"+encodeURIComponent(input.sessionID)+"/compact",url),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({})});if(!response.ok)throw new Error("Host compaction request failed ("+response.status+"); previous history is retained");const payload=await response.json() as any;if(typeof payload?.data?.id!=="string"||payload.data.sessionID!==input.sessionID||payload.data.type!=="compaction")throw new Error("Host did not return the admitted compaction record; reconcile before retrying");return {receipt:payload.data.id}}}
